"use client";

import { Check, Copy, FileUp, KeyRound, RefreshCw, RotateCcw, Send, ShieldCheck, Webhook } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { apiFetch, type AuthView } from "@/lib/api-client";

type Scope = "content:read" | "content:write" | "content:schedule" | "proof:read" | "imports:write" | "events:read" | "events:manage";
type Topic = "system.test" | "content.created" | "draft.revised" | "approval.needed" | "approval.decided" | "target.scheduled" | "target.rescheduled" | "target.cancelled" | "publish.succeeded" | "publish.failed" | "publish.action_required" | "proof.created";
type ApiKeyView = { id: string; name: string; keyPrefix: string; scopes: Scope[]; brandIds: string[]; accountIds: string[]; createdAt: string; expiresAt?: string; lastUsedAt?: string; revokedAt?: string };
type Subscription = { id: string; name: string; url: string; topics: Topic[]; brandIds: string[]; active: boolean; createdAt: string; disabledAt?: string };
type EventView = { id: string; topic: Topic; brandId?: string; contentItemId?: string; occurredAt: string; actorType: string };
type Delivery = { id: string; subscriptionId: string; eventId: string; status: "pending" | "processing" | "delivered" | "failed" | "dead_letter"; attempts: number; responseStatus?: number; lastError?: string; createdAt: string };
type ImportSession = { id: string; status: "staged" | "processing" | "committed" | "failed"; rows: Array<{ rowNumber: number; externalRef: string; title: string; status: "valid" | "invalid" | "created" | "existing" | "failed"; errors: string[]; contentItemId?: string }> };

const scopeChoices: Array<{ value: Scope; label: string }> = [
  { value: "content:read", label: "Read content" }, { value: "content:write", label: "Create and edit drafts" }, { value: "content:schedule", label: "Schedule approved posts" },
  { value: "proof:read", label: "Read publish proof" }, { value: "imports:write", label: "Import CSV or JSON" }, { value: "events:read", label: "Read events" }, { value: "events:manage", label: "Manage webhooks" },
];
const topicChoices: Topic[] = ["content.created", "draft.revised", "approval.needed", "approval.decided", "target.scheduled", "target.rescheduled", "target.cancelled", "publish.succeeded", "publish.failed", "publish.action_required", "proof.created"];

async function responseError(response: Response, fallback: string) { const body = await response.json().catch(() => ({})) as { message?: string | string[] }; return Array.isArray(body.message) ? body.message.join(" ") : body.message ?? fallback }

export function AutomationGateway({ auth, workspaceId, brandId }: { auth: AuthView; workspaceId: string; brandId: string }) {
  const [keys, setKeys] = useState<ApiKeyView[]>([]); const [subscriptions, setSubscriptions] = useState<Subscription[]>([]); const [events, setEvents] = useState<EventView[]>([]); const [deliveries, setDeliveries] = useState<Delivery[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [keyFormOpen, setKeyFormOpen] = useState(false); const [webhookFormOpen, setWebhookFormOpen] = useState(false); const [newSecret, setNewSecret] = useState<{ label: string; value: string } | null>(null); const [copied, setCopied] = useState(false);
  const [importKey, setImportKey] = useState(""); const [importFormat, setImportFormat] = useState<"csv" | "json">("csv"); const [importPayload, setImportPayload] = useState("externalRef,title,summary,riskLevel\nsource-001,First imported story,Add facts before review,medium"); const [importSession, setImportSession] = useState<ImportSession | null>(null); const [importBusy, setImportBusy] = useState(false);
  const membership = auth.memberships.find((entry) => entry.workspaceId === workspaceId) ?? auth.memberships[0]; const isOwner = membership?.role === "owner"; const canManage = isOwner || membership?.role === "manager";

  const load = useCallback(async () => {
    if (!canManage) { setLoading(false); return; } setLoading(true); setError("");
    try {
      const query = `workspaceId=${encodeURIComponent(workspaceId)}`; const responses = await Promise.all(["keys", "subscriptions", "events", "deliveries"].map((path) => apiFetch(`/v1/automation/${path}?${query}`, { cache: "no-store" }, auth.csrfToken)));
      if (responses.some((response) => !response.ok)) throw new Error("Could not load Developer API settings.");
      setKeys(await responses[0]!.json() as ApiKeyView[]); setSubscriptions(await responses[1]!.json() as Subscription[]); setEvents(await responses[2]!.json() as EventView[]); setDeliveries(await responses[3]!.json() as Delivery[]);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load Developer API settings."); } finally { setLoading(false); }
  }, [auth.csrfToken, canManage, workspaceId]);
  useEffect(() => { void load() }, [load]);

  async function createKey(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const scopes = form.getAll("scopes") as Scope[]; setError("");
    const response = await apiFetch(`/v1/automation/keys?workspaceId=${encodeURIComponent(workspaceId)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name"), scopes, brandIds: [brandId], accountIds: [] }) }, auth.csrfToken);
    if (!response.ok) { setError(await responseError(response, "Could not create the API key.")); return }
    const body = await response.json() as { secret: string }; setNewSecret({ label: "API key", value: body.secret }); if (scopes.includes("imports:write")) setImportKey(body.secret); setKeyFormOpen(false); setCopied(false); await load();
  }
  async function revokeKey(key: ApiKeyView) { if (!window.confirm(`Revoke ${key.name}? Its next API call will stop immediately.`)) return; const response = await apiFetch(`/v1/automation/keys/${key.id}/revoke?workspaceId=${encodeURIComponent(workspaceId)}`, { method: "POST" }, auth.csrfToken); if (!response.ok) setError(await responseError(response, "Could not revoke this key.")); else await load() }
  async function createWebhook(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const topics = form.getAll("topics") as Topic[]; setError("");
    const response = await apiFetch(`/v1/automation/subscriptions?workspaceId=${encodeURIComponent(workspaceId)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name"), url: form.get("url"), topics, brandIds: [brandId] }) }, auth.csrfToken);
    if (!response.ok) { setError(await responseError(response, "Could not create the webhook.")); return }
    const body = await response.json() as { signingSecret: string }; setNewSecret({ label: "Webhook signing secret", value: body.signingSecret }); setWebhookFormOpen(false); setCopied(false); await load();
  }
  async function testWebhook(subscription: Subscription) { const response = await apiFetch(`/v1/automation/subscriptions/${subscription.id}/test?workspaceId=${encodeURIComponent(workspaceId)}`, { method: "POST" }, auth.csrfToken); if (!response.ok) setError(await responseError(response, "Could not queue a test event.")); else await load() }
  async function disableWebhook(subscription: Subscription) { const response = await apiFetch(`/v1/automation/subscriptions/${subscription.id}/disable?workspaceId=${encodeURIComponent(workspaceId)}`, { method: "POST" }, auth.csrfToken); if (!response.ok) setError(await responseError(response, "Could not disable this webhook.")); else await load() }
  async function retryDelivery(delivery: Delivery) { const response = await apiFetch(`/v1/automation/deliveries/${delivery.id}/retry?workspaceId=${encodeURIComponent(workspaceId)}`, { method: "POST" }, auth.csrfToken); if (!response.ok) setError(await responseError(response, "Could not retry this delivery.")); else await load() }
  async function copySecret() { if (!newSecret) return; await navigator.clipboard.writeText(newSecret.value); setCopied(true) }
  async function previewImport(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setImportBusy(true);
    try { let body: Record<string, unknown> = { format: importFormat, brandId }; if (importFormat === "csv") body.data = importPayload; else { const parsed = JSON.parse(importPayload) as unknown; if (!Array.isArray(parsed)) throw new Error("JSON must be an array of rows."); body.rows = parsed }
      const response = await apiFetch("/public/v1/imports/preview", { method: "POST", headers: { authorization: `Bearer ${importKey.trim()}`, "content-type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await responseError(response, "Could not preview this import.")); const result = await response.json() as { data: ImportSession }; setImportSession(result.data);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not preview this import.") } finally { setImportBusy(false) }
  }
  async function commitImport() { if (!importSession) return; setError(""); setImportBusy(true); try { const response = await apiFetch(`/public/v1/imports/${importSession.id}/commit`, { method: "POST", headers: { authorization: `Bearer ${importKey.trim()}` } }); if (!response.ok) throw new Error(await responseError(response, "Could not commit this import.")); const result = await response.json() as { data: ImportSession }; setImportSession(result.data) } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not commit this import.") } finally { setImportBusy(false) } }

  if (!canManage) return <section className="module-page"><div className="module-hero"><div><p className="eyebrow">WORKSPACE MODULE</p><h1>Developer API</h1><p>Ask a manager or owner for access to automation settings.</p></div></div></section>;
  return <section className="module-page">
    <div className="module-hero"><div><p className="eyebrow">AUTOMATION GATEWAY</p><h1>Developer API</h1><p>Connect n8n, scripts, or another trusted system without sharing an owner login.</p></div><div className="module-actions"><button className="secondary-button" onClick={() => void load()}><RefreshCw size={15} /> Refresh</button>{isOwner ? <button className="secondary-button" onClick={() => setWebhookFormOpen((value) => !value)}><Webhook size={15} /> New webhook</button> : null}{isOwner ? <button className="new-button" onClick={() => setKeyFormOpen((value) => !value)}><KeyRound size={15} /> New API key</button> : null}</div></div>
    {error ? <div className="module-alert" role="alert">{error}</div> : null}
    {newSecret ? <div className="gateway-secret panel" role="status"><ShieldCheck size={20} /><div><strong>Copy this {newSecret.label} now</strong><p>It is shown only once. OriginPost stores a hash or encrypted copy, never this plain value.</p><code>{newSecret.value}</code></div><button className="secondary-button" onClick={() => void copySecret()}>{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? "Copied" : "Copy"}</button></div> : null}
    {keyFormOpen ? <form className="gateway-form panel" onSubmit={createKey}><div><h2>Create a scoped API key</h2><p>Start small. You can create another key for a different job.</p></div><label>Key name<input name="name" placeholder="Example: n8n newsroom intake" required maxLength={100} /></label><fieldset><legend>Allowed actions</legend><div className="gateway-checks">{scopeChoices.map((scope) => <label key={scope.value}><input type="checkbox" name="scopes" value={scope.value} defaultChecked={["content:read", "content:write", "proof:read"].includes(scope.value)} /><span>{scope.label}</span></label>)}</div></fieldset><p className="gateway-scope-note">This key will be limited to the active brand. Imported work still needs human approval.</p><button className="new-button">Create and show key</button></form> : null}
    {webhookFormOpen ? <form className="gateway-form panel" onSubmit={createWebhook}><div><h2>Add a signed webhook</h2><p>OriginPost retries safely and never repeats the social publish because a callback failed.</p></div><div className="gateway-form-row"><label>Name<input name="name" placeholder="Example: n8n status update" required /></label><label>HTTPS URL<input name="url" type="url" placeholder="https://automation.example.com/originpost" required /></label></div><fieldset><legend>Events to send</legend><div className="gateway-checks gateway-topic-checks">{topicChoices.map((topic) => <label key={topic}><input type="checkbox" name="topics" value={topic} defaultChecked={["approval.needed", "publish.succeeded", "publish.failed", "proof.created"].includes(topic)} /><span>{topic.replaceAll(".", " ")}</span></label>)}</div></fieldset><button className="new-button">Create and show signing secret</button></form> : null}
    <div className="gateway-overview">
      <article className="panel gateway-card"><div className="gateway-card-head"><span><KeyRound size={17} /></span><div><h2>API keys</h2><p>{keys.filter((key) => !key.revokedAt).length} active</p></div></div><div className="gateway-list">{keys.map((key) => <div key={key.id}><div><strong>{key.name}</strong><small>{key.keyPrefix}… · {key.scopes.join(" · ")}</small><em>{key.revokedAt ? "Revoked" : key.lastUsedAt ? `Used ${new Date(key.lastUsedAt).toLocaleString()}` : "Not used yet"}</em></div>{isOwner && !key.revokedAt ? <button onClick={() => void revokeKey(key)}>Revoke</button> : null}</div>)}{!loading && !keys.length ? <p>No API keys yet.</p> : null}</div></article>
      <article className="panel gateway-card"><div className="gateway-card-head"><span><Webhook size={17} /></span><div><h2>Webhooks</h2><p>{subscriptions.filter((item) => item.active).length} active</p></div></div><div className="gateway-list">{subscriptions.map((subscription) => <div key={subscription.id}><div><strong>{subscription.name}</strong><small>{subscription.url}</small><em>{subscription.active ? subscription.topics.join(" · ") : "Disabled"}</em></div>{subscription.active ? <span className="gateway-row-actions"><button onClick={() => void testWebhook(subscription)}><Send size={13} /> Test</button>{isOwner ? <button onClick={() => void disableWebhook(subscription)}>Disable</button> : null}</span> : null}</div>)}{!loading && !subscriptions.length ? <p>No webhooks yet.</p> : null}</div></article>
    </div>
    <div className="panel gateway-explorer"><div className="module-list-head"><div><h2>Event delivery</h2><p>Every event keeps one ID, delivery state, attempt count, and replay history.</p></div><span>{events.length} events · {deliveries.length} deliveries</span></div><div className="gateway-delivery-list">{deliveries.slice(0, 12).map((delivery) => { const event = events.find((entry) => entry.id === delivery.eventId); return <div key={delivery.id}><span className={`delivery-state ${delivery.status}`}>{delivery.status.replace("_", " ")}</span><div><strong>{event?.topic ?? delivery.eventId}</strong><small>{new Date(delivery.createdAt).toLocaleString()} · attempt {delivery.attempts}{delivery.responseStatus ? ` · HTTP ${delivery.responseStatus}` : ""}</small>{delivery.lastError ? <em>{delivery.lastError}</em> : null}</div>{(delivery.status === "failed" || delivery.status === "dead_letter") ? <button onClick={() => void retryDelivery(delivery)}><RotateCcw size={13} /> Retry</button> : null}</div>})}{!loading && !deliveries.length ? <div className="module-empty"><Webhook size={22} /><strong>No delivery attempts yet</strong><p>Create a webhook, then send a test event.</p></div> : null}</div></div>
    <div className="panel gateway-quickstart"><p className="eyebrow">QUICK START</p><h2>Create a safe draft from curl or n8n</h2><p>The same Idempotency-Key returns the same Content Item. It never creates a duplicate.</p><pre>{`curl -X POST http://localhost:4000/public/v1/content-items \\\n  -H "Authorization: Bearer <API_KEY>" \\\n  -H "Idempotency-Key: source-row-123" \\\n  -H "Content-Type: application/json" \\\n  -d '{"brandId":"${brandId}","title":"New source-backed item"}'`}</pre></div>
    <form className="panel gateway-form" onSubmit={previewImport}><div className="gateway-card-head"><span><FileUp size={17} /></span><div><h2>Stage a CSV or JSON import</h2><p>Preview first. Invalid rows create nothing. A commit only creates safe inbox items for human review.</p></div></div><div className="gateway-form-row"><label>Format<select value={importFormat} onChange={(event) => { const format = event.target.value as "csv" | "json"; setImportFormat(format); setImportPayload(format === "csv" ? "externalRef,title,summary,riskLevel\nsource-001,First imported story,Add facts before review,medium" : '[{"externalRef":"source-001","title":"First imported story","summary":"Add facts before review","riskLevel":"medium"}]'); setImportSession(null) }}><option value="csv">CSV</option><option value="json">JSON</option></select></label><label>API key with imports:write<input type="password" value={importKey} onChange={(event) => setImportKey(event.target.value)} placeholder="op_live_…" required autoComplete="off" /></label></div><label>Rows<textarea value={importPayload} onChange={(event) => { setImportPayload(event.target.value); setImportSession(null) }} spellCheck={false} required /></label><button className="secondary-button" disabled={importBusy}>{importBusy ? "Working…" : "Preview without creating"}</button>{importSession ? <div className="gateway-import-result"><p><strong>{importSession.rows.filter((row) => row.status !== "invalid").length}</strong> ready · <strong>{importSession.rows.filter((row) => row.status === "invalid").length}</strong> invalid · status <strong>{importSession.status}</strong></p>{importSession.rows.slice(0, 8).map((row) => <div key={row.rowNumber}><span>Row {row.rowNumber}</span><span><strong>{row.title || row.externalRef || "Invalid row"}</strong><small>{row.errors.join(" ") || row.contentItemId || row.externalRef}</small></span><em>{row.status}</em></div>)}{importSession.status === "staged" ? <button className="new-button" type="button" onClick={() => void commitImport()} disabled={importBusy}>Commit valid rows to Inbox</button> : null}</div> : null}</form>
  </section>;
}
