import { materializeEvergreenOccurrence, nextEvergreenTime, type ContentItemRepository, type EvergreenOccurrence, type EvergreenRepository, type NotificationRepository } from "@originpost/domain";
import { createNotification } from "@originpost/domain";

export interface EvergreenWorkerDependencies { repository:ContentItemRepository; evergreenRepository:EvergreenRepository; notificationRepository:NotificationRepository; now?:()=>Date; owner?:string; startImmediately?:boolean; }
export function createEvergreenRuntime(deps:EvergreenWorkerDependencies){
  const clock=deps.now??(()=>new Date());const owner=deps.owner??`evergreen-worker-${process.pid}`;let running=false;
  const linkPublishedProofs=async()=>{const waiting=await deps.evergreenRepository.listOccurrencesAwaitingProof(100);let linked=0;for(const occurrence of waiting){const entry=await deps.evergreenRepository.get(occurrence.workspaceId,occurrence.entryId);const item=await deps.repository.get(occurrence.workspaceId,occurrence.contentItemId);if(!entry||!item)continue;const proof=item.proofs.filter((value)=>value.platform===entry.platform&&value.accountId===entry.accountId).sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt))[0];if(proof&&await deps.evergreenRepository.linkPublishedOccurrence({workspaceId:occurrence.workspaceId,id:occurrence.id,proofId:proof.id,at:clock().toISOString()}))linked+=1;}return linked;};
  const run=async()=>{if(running)return {skipped:true};running=true;try{const linked=await linkPublishedProofs();const now=clock();const claimed=await deps.evergreenRepository.claimDue({owner,before:new Date(now.getTime()+24*60*60_000).toISOString(),limit:25,leaseSeconds:120});for(const entry of claimed){try{const source=await deps.repository.get(entry.workspaceId,entry.sourceContentItemId);if(!source)throw new Error("The original Content Item is unavailable.");const created=materializeEvergreenOccurrence(entry,source,now.toISOString());const existing=await deps.repository.get(entry.workspaceId,created.item.id);if(existing){if(!existing.tags.includes(`evergreen:${entry.id}`))throw new Error("A different Content Item uses the deterministic reuse identity.");}else await deps.repository.commit(created.item,created.event);const next=nextEvergreenTime(entry);const completed=await deps.evergreenRepository.completeClaim({workspaceId:entry.workspaceId,id:entry.id,claimId:entry.claimId!,occurrence:created.occurrence,nextPublishAt:next.nextPublishAt,completed:next.completed,at:clock().toISOString()});if(completed)await deps.notificationRepository.create(createNotification({workspaceId:entry.workspaceId,kind:"approval_needed",severity:"info",title:"A refreshed post is ready",body:`${entry.name} created a new draft. Check facts, media rights, and wording before approval.`,dedupeKey:`evergreen:${entry.id}:occurrence:${created.occurrence.occurrenceNo}:review`,contentItemId:created.item.id,actionUrl:`/?content=${encodeURIComponent(created.item.id)}`}));}catch(error){const at=clock().toISOString();const occurrence:EvergreenOccurrence={id:`evergreen_occurrence_failed_${entry.id}_${entry.pendingOccurrenceNo}`,workspaceId:entry.workspaceId,brandId:entry.brandId,entryId:entry.id,occurrenceNo:entry.pendingOccurrenceNo!,scheduledFor:entry.nextPublishAt,mode:entry.mode,status:"failed",contentItemId:entry.pendingContentItemId!,error:error instanceof Error?error.message.slice(0,500):"Unknown reuse error",createdAt:at,updatedAt:at};const failed=await deps.evergreenRepository.failClaim({workspaceId:entry.workspaceId,id:entry.id,claimId:entry.claimId!,occurrence,at});if(failed)await deps.notificationRepository.create(createNotification({workspaceId:entry.workspaceId,kind:"action_required",severity:"error",title:"Reuse cycle paused",body:`${entry.name} could not prepare its next draft. Review the source post and policy.`,dedupeKey:`evergreen:${entry.id}:occurrence:${occurrence.occurrenceNo}:failed`,contentItemId:entry.sourceContentItemId,actionUrl:"/?module=evergreen"}));}}return {claimed:claimed.length,linked};}finally{running=false;}};
  const timer=setInterval(()=>void run().catch((error)=>console.error("Evergreen refresh failed:",error instanceof Error?error.message:"Unknown error")),5*60_000);if(deps.startImmediately!==false)void run();return {run,close(){clearInterval(timer);}};
}
