import {
  DomainError,
  type ContentItemRepository,
  type CurrentCollaboratorStatusSnapshot,
  type InstagramCollaboratorCandidate,
  type InstagramCollaboratorPoll,
  type InstagramCollaboratorRepository,
  type InstagramCollaboratorStatusView,
  instagramRequestedUsernamesHash,
} from "@originpost/domain";
import type { Sql } from "postgres";
import { randomUUID } from "node:crypto";

type CandidateRow = { payload: InstagramCollaboratorCandidate };
type PollRow = { payload: InstagramCollaboratorPoll };
type SnapshotRow = { payload: CurrentCollaboratorStatusSnapshot };

export class InMemoryInstagramCollaboratorRepository implements InstagramCollaboratorRepository {
  private readonly candidates = new Map<string, InstagramCollaboratorCandidate>();
  private readonly polls = new Map<string, InstagramCollaboratorPoll>();
  private readonly snapshots = new Map<string, CurrentCollaboratorStatusSnapshot[]>();
  constructor(
    private readonly content: ContentItemRepository,
    private readonly clock: () => Date = () => new Date(),
  ) {}
  async createCandidate(value: InstagramCollaboratorCandidate) {
    if (this.candidates.has(value.id)) throw new DomainError("This collaborator candidate already exists.", "instagram_collaborator_candidate_exists", 409);
    this.candidates.set(value.id, structuredClone(value)); return structuredClone(value);
  }
  async getCandidate(workspaceId:string,contentItemId:string,candidateId:string){const value=this.candidates.get(candidateId);return value?.workspaceId===workspaceId&&value.contentItemId===contentItemId?structuredClone(value):null;}
  async getApprovedCandidate(workspaceId:string,contentItemId:string,approvalId:string){const value=[...this.candidates.values()].find((entry)=>entry.workspaceId===workspaceId&&entry.contentItemId===contentItemId&&entry.status==="approved"&&entry.approvalId===approvalId);return value?structuredClone(value):null;}
  async listCandidates(workspaceId:string,contentItemId:string){return structuredClone([...this.candidates.values()].filter((entry)=>entry.workspaceId===workspaceId&&entry.contentItemId===contentItemId).sort((a,b)=>b.requestedAt.localeCompare(a.requestedAt)));}
  async approveCandidate(workspaceId:string,contentItemId:string,candidateId:string,approval:{id:string;actorId:string;createdAt:string}){
    const current=await this.getCandidate(workspaceId,contentItemId,candidateId);if(!current)throw new DomainError("Collaborator candidate not found.","instagram_collaborator_candidate_not_found",404);
    if(current.status==="approved"){if(current.approvalId!==approval.id)throw new DomainError("This candidate was already approved.","instagram_collaborator_candidate_already_approved",409);return current;}
    const next={...current,status:"approved" as const,approvalId:approval.id,approvedBy:approval.actorId,approvedAt:approval.createdAt};this.candidates.set(candidateId,structuredClone(next));return next;
  }
  async commitCandidateApproval(workspaceId:string,contentItemId:string,candidateId:string,result:{item:import("@originpost/domain").ContentItem;approval:import("@originpost/domain").Approval;event:import("@originpost/domain").AuditEvent}){const current=await this.getCandidate(workspaceId,contentItemId,candidateId);if(!current)throw new DomainError("Collaborator candidate not found.","instagram_collaborator_candidate_not_found",404);if(current.status==="approved"){if(current.approvalId!==result.approval.id)throw new DomainError("This candidate was already approved.","instagram_collaborator_candidate_already_approved",409);return current;}await this.content.commit(result.item,result.event);return this.approveCandidate(workspaceId,contentItemId,candidateId,{id:result.approval.id,actorId:result.approval.actorId,createdAt:result.approval.createdAt});}
  async createPollFromStoredProof(workspaceId:string,contentItemId:string,proofId:string,options:{nextAttemptAt:string;expiresAt:string;maxAttempts:number}){
    const existing=this.polls.get(proofId);if(existing)return existing.workspaceId===workspaceId&&existing.contentItemId===contentItemId?structuredClone(existing):null;
    const item=await this.content.get(workspaceId,contentItemId);const proof=item?.proofs.find((entry)=>entry.id===proofId);
    const target=item?.targets.find((entry)=>entry.platform==="instagram"&&entry.accountId===proof?.accountId&&entry.draftId===proof?.draftId&&entry.status==="published");const invite=proof?.collaboratorInviteProof;const binding=(target?.settings&&"approvalBinding" in target.settings?target.settings.approvalBinding:undefined) as {approvedSettingsSha256?:string;accountId?:string;draftSha256?:string}|undefined;const targetUsernames=target?.settings&&"collaborators" in target.settings&&Array.isArray(target.settings.collaborators)?target.settings.collaborators as string[]:undefined;if(!item||!proof||proof.platform!=="instagram"||invite?.requestState!=="requested_unverified"||instagramRequestedUsernamesHash(invite.requestedUsernames)!==invite.requestedUsernamesSha256||!targetUsernames||instagramRequestedUsernamesHash(targetUsernames)!==invite.requestedUsernamesSha256||!proof.approvedSettingsSha256||!binding||binding.approvedSettingsSha256!==proof.approvedSettingsSha256||binding.accountId!==proof.accountId||binding.draftSha256!==proof.draftSha256)return null;
    const requestedInvite=invite as InstagramCollaboratorPoll["inviteProof"];
    const now=new Date().toISOString();const poll:InstagramCollaboratorPoll={workspaceId,brandId:item.brandId,contentItemId,proofId,accountId:proof.accountId,externalMediaId:proof.externalPostId,inviteProof:requestedInvite,status:"pending",attemptCount:0,maxAttempts:options.maxAttempts,nextAttemptAt:options.nextAttemptAt,expiresAt:options.expiresAt,updatedAt:now};this.polls.set(proofId,structuredClone(poll));return poll;
  }
  async recoverMissingPolls(){return 0;}
  async claimDuePolls(owner:string,_now:string,limit:number,leaseSeconds:number){const now=this.clock();const nowIso=now.toISOString();const due=[...this.polls.values()].filter((entry)=>["pending","processing","unavailable"].includes(entry.status)&&entry.nextAttemptAt<=nowIso&&entry.expiresAt>nowIso&&entry.attemptCount<entry.maxAttempts&&(!entry.claimLeaseExpiresAt||entry.claimLeaseExpiresAt<=nowIso)).slice(0,limit).map((entry)=>({...entry,status:"processing" as const,attemptCount:entry.attemptCount+1,claimId:`${owner}:${randomUUID()}`,claimLeaseExpiresAt:new Date(now.getTime()+leaseSeconds*1000).toISOString(),updatedAt:nowIso}));for(const poll of due)this.polls.set(poll.proofId,structuredClone(poll));return structuredClone(due);}
  async recordPollResult(poll:InstagramCollaboratorPoll,result:{snapshots:CurrentCollaboratorStatusSnapshot[];providerReadComplete:boolean;trackingComplete:boolean;availability:string;capturedAt:string;rawResponseSha256?:string;retryAt?:string;errorSummary?:string}){const current=this.polls.get(poll.proofId);const nowIso=this.clock().toISOString();if(!poll.claimId||current?.claimId!==poll.claimId||current.status!=="processing"||!current.claimLeaseExpiresAt||current.claimLeaseExpiresAt<=nowIso)throw new DomainError("This collaborator status lease is stale.","instagram_collaborator_poll_lease_lost",409);this.validateSnapshots(poll,result.snapshots,result.providerReadComplete);const expired=!result.trackingComplete&&(!result.retryAt||poll.attemptCount>=poll.maxAttempts||result.retryAt>=poll.expiresAt);const {claimId:_,claimLeaseExpiresAt:__,...withoutClaim}=poll;const next={...withoutClaim,status:result.trackingComplete?"complete" as const:expired?"expired" as const:result.availability==="available"?"pending" as const:"unavailable" as const,nextAttemptAt:result.retryAt??poll.nextAttemptAt,availability:result.availability,capturedAt:result.capturedAt,latestReadComplete:result.providerReadComplete,...(result.rawResponseSha256?{rawResponseSha256:result.rawResponseSha256}:{rawResponseSha256:undefined}),...(result.errorSummary?{errorSummary:result.errorSummary}:{errorSummary:undefined}),updatedAt:result.capturedAt};this.polls.set(poll.proofId,next);this.snapshots.set(poll.proofId,structuredClone(result.snapshots));}
  private validateSnapshots(poll:InstagramCollaboratorPoll,snapshots:CurrentCollaboratorStatusSnapshot[],providerReadComplete:boolean){const requested=new Set(poll.inviteProof.requestedUsernames);const seen=new Set<string>();for(const snapshot of snapshots){if(seen.has(snapshot.username)||!requested.has(snapshot.username)||snapshot.workspaceId!==poll.workspaceId||snapshot.brandId!==poll.brandId||snapshot.contentItemId!==poll.contentItemId||snapshot.proofId!==poll.proofId||snapshot.accountId!==poll.accountId||snapshot.externalMediaId!==poll.externalMediaId||snapshot.requestedUsernamesSha256!==poll.inviteProof.requestedUsernamesSha256)throw new Error("Instagram collaborator snapshot lineage mismatch.");seen.add(snapshot.username);}if(providerReadComplete&&(seen.size!==requested.size||[...requested].some((username)=>!seen.has(username))))throw new Error("A complete collaborator provider read must include each requested username exactly once.");}
  async getStatus(workspaceId:string,contentItemId:string,proofId:string):Promise<InstagramCollaboratorStatusView>{const poll=this.polls.get(proofId);if(!poll||poll.workspaceId!==workspaceId||poll.contentItemId!==contentItemId)return{poll:null,snapshots:[]};const {claimId:_,claimLeaseExpiresAt:__,...safePoll}=poll;return{poll:structuredClone(safePoll),snapshots:structuredClone(this.snapshots.get(proofId)??[])}};
}

export class PostgresInstagramCollaboratorRepository implements InstagramCollaboratorRepository {
  constructor(private readonly sql:Sql){}
  async createCandidate(value:InstagramCollaboratorCandidate){
    const rows=await this.sql<CandidateRow[]>`insert into instagram_collaborator_candidates (id,workspace_id,brand_id,content_item_id,draft_id,draft_sha256,account_id,approved_settings_sha256,status,requested_by,requested_at,payload) values (${value.id},${value.workspaceId},${value.brandId},${value.contentItemId},${value.draftId},${value.draftSha256},${value.accountId},${value.settings.approvedSettingsSha256},${value.status},${value.requestedBy},${value.requestedAt},${this.sql.json(value as never)}) on conflict do nothing returning payload`;
    if(!rows[0])throw new DomainError("This collaborator candidate already exists.","instagram_collaborator_candidate_exists",409);return rows[0].payload;
  }
  async getCandidate(workspaceId:string,contentItemId:string,candidateId:string){const rows=await this.sql<CandidateRow[]>`select payload from instagram_collaborator_candidates where id=${candidateId} and workspace_id=${workspaceId} and content_item_id=${contentItemId} limit 1`;return rows[0]?.payload??null;}
  async getApprovedCandidate(workspaceId:string,contentItemId:string,approvalId:string){const rows=await this.sql<CandidateRow[]>`select payload from instagram_collaborator_candidates where workspace_id=${workspaceId} and content_item_id=${contentItemId} and approval_id=${approvalId} and status='approved' limit 1`;return rows[0]?.payload??null;}
  async listCandidates(workspaceId:string,contentItemId:string){const rows=await this.sql<CandidateRow[]>`select payload from instagram_collaborator_candidates where workspace_id=${workspaceId} and content_item_id=${contentItemId} order by requested_at desc`;return rows.map((row)=>row.payload);}
  async approveCandidate(workspaceId:string,contentItemId:string,candidateId:string,approval:{id:string;actorId:string;createdAt:string}){
    return this.sql.begin(async(sql)=>{const rows=await sql<CandidateRow[]>`select payload from instagram_collaborator_candidates where id=${candidateId} and workspace_id=${workspaceId} and content_item_id=${contentItemId} limit 1 for update`;const current=rows[0]?.payload;if(!current)throw new DomainError("Collaborator candidate not found.","instagram_collaborator_candidate_not_found",404);if(current.status==="approved"){if(current.approvalId!==approval.id)throw new DomainError("This candidate was already approved.","instagram_collaborator_candidate_already_approved",409);return current;}const next={...current,status:"approved" as const,approvalId:approval.id,approvedBy:approval.actorId,approvedAt:approval.createdAt};await sql`update instagram_collaborator_candidates set status='approved',approval_id=${approval.id},approved_by=${approval.actorId},approved_at=${approval.createdAt},payload=${sql.json(next as never)} where id=${candidateId} and workspace_id=${workspaceId} and content_item_id=${contentItemId} and status='pending_approval'`;return next;});
  }
  async commitCandidateApproval(workspaceId:string,contentItemId:string,candidateId:string,result:{item:import("@originpost/domain").ContentItem;approval:import("@originpost/domain").Approval;event:import("@originpost/domain").AuditEvent}){return this.sql.begin(async(sql)=>{const rows=await sql<CandidateRow[]>`select payload from instagram_collaborator_candidates where id=${candidateId} and workspace_id=${workspaceId} and content_item_id=${contentItemId} limit 1 for update`;const current=rows[0]?.payload;if(!current)throw new DomainError("Collaborator candidate not found.","instagram_collaborator_candidate_not_found",404);if(current.status==="approved"){if(current.approvalId!==result.approval.id)throw new DomainError("This candidate was already approved.","instagram_collaborator_candidate_already_approved",409);return current;}if(result.item.workspaceId!==workspaceId||result.item.id!==contentItemId||result.event.workspaceId!==workspaceId||result.event.contentItemId!==contentItemId)throw new Error("Collaborator approval transaction lineage mismatch.");const committed=await sql<{id:string}[]>`update content_items set version=${result.item.version},status=${result.item.status},payload=${sql.json(result.item as never)},updated_at=${result.item.updatedAt} where id=${contentItemId} and workspace_id=${workspaceId} and version=${result.item.version-1} returning id`;if(!committed[0])throw new DomainError("This content changed while you were working. Refresh it and try again.","content_version_conflict",409);await sql`insert into approvals (id,workspace_id,content_item_id,actor_id,decision,note,draft_id,draft_sha256,created_at,payload) values (${result.approval.id},${workspaceId},${contentItemId},${result.approval.actorId},${result.approval.decision},${result.approval.note??null},${result.approval.draftId},${result.approval.draftSha256},${result.approval.createdAt},${sql.json(result.approval as never)})`;await sql`insert into audit_events (id,workspace_id,content_item_id,actor_id,actor_type,action,detail,created_at) values (${result.event.id},${workspaceId},${contentItemId},${result.event.actorId},${result.event.actorType},${result.event.action},${sql.json({...result.event.detail,contentVersion:result.item.version} as never)},${result.event.createdAt})`;const next={...current,status:"approved" as const,approvalId:result.approval.id,approvedBy:result.approval.actorId,approvedAt:result.approval.createdAt};await sql`update instagram_collaborator_candidates set status='approved',approval_id=${result.approval.id},approved_by=${result.approval.actorId},approved_at=${result.approval.createdAt},payload=${sql.json(next as never)} where id=${candidateId} and workspace_id=${workspaceId} and content_item_id=${contentItemId} and status='pending_approval'`;return next;});}
  async createPollFromStoredProof(workspaceId:string,contentItemId:string,proofId:string,options:{nextAttemptAt:string;expiresAt:string;maxAttempts:number}){
    const rows=await this.sql<{proof:Record<string,unknown>;brand_id:string;account_id:string;external_post_id:string;target:Record<string,unknown>|null}[]>`select p.payload as proof,c.brand_id,p.account_id,p.external_post_id,(select t.payload from publish_targets t where t.workspace_id=p.workspace_id and t.content_item_id=p.content_item_id and t.platform='instagram' and t.account_id=p.account_id and t.status='published' and t.payload->>'draftId'=p.payload->>'draftId' and t.payload->'settings'->>'approvedSettingsSha256'=p.payload->>'approvedSettingsSha256' limit 1) as target from publish_proofs p join content_items c on c.id=p.content_item_id and c.workspace_id=p.workspace_id join connected_accounts a on a.id=p.account_id and a.workspace_id=p.workspace_id and a.brand_id=c.brand_id where p.id=${proofId} and p.workspace_id=${workspaceId} and p.content_item_id=${contentItemId} and p.platform='instagram' limit 1`;
    const row=rows[0];const invite=row?.proof.collaboratorInviteProof as InstagramCollaboratorPoll["inviteProof"]|undefined;const proofAccount=row?.proof.accountId;const proofExternal=row?.proof.externalPostId;const proofDraft=row?.proof.draftSha256;const approvedHash=row?.proof.approvedSettingsSha256;const targetSettings=row?.target?.settings as Record<string,unknown>|undefined;const targetUsernames=targetSettings?.collaborators;const binding=targetSettings?.approvalBinding as Record<string,unknown>|undefined;if(!row||!invite||invite.requestState!=="requested_unverified"||!Array.isArray(invite.requestedUsernames)||invite.requestedUsernames.some((value)=>typeof value!=="string")||typeof invite.requestedUsernamesSha256!=="string"||instagramRequestedUsernamesHash(invite.requestedUsernames as string[])!==invite.requestedUsernamesSha256||!Array.isArray(targetUsernames)||targetUsernames.some((value)=>typeof value!=="string")||instagramRequestedUsernamesHash(targetUsernames as string[])!==invite.requestedUsernamesSha256||proofAccount!==row.account_id||proofExternal!==row.external_post_id||typeof proofDraft!=="string"||typeof approvedHash!=="string"||binding?.approvedSettingsSha256!==approvedHash||binding.accountId!==row.account_id||binding.draftSha256!==proofDraft)return null;
    const now=new Date().toISOString();const poll:InstagramCollaboratorPoll={workspaceId,brandId:row.brand_id,contentItemId,proofId,accountId:row.account_id,externalMediaId:row.external_post_id,inviteProof:invite,status:"pending",attemptCount:0,maxAttempts:options.maxAttempts,nextAttemptAt:options.nextAttemptAt,expiresAt:options.expiresAt,updatedAt:now};
    const inserted=await this.sql<PollRow[]>`insert into instagram_collaborator_polls (proof_id,workspace_id,brand_id,content_item_id,account_id,external_media_id,requested_usernames_sha256,status,attempt_count,max_attempts,next_attempt_at,expires_at,payload,created_at,updated_at) values (${proofId},${workspaceId},${poll.brandId},${contentItemId},${poll.accountId},${poll.externalMediaId},${invite.requestedUsernamesSha256},'pending',0,${options.maxAttempts},${options.nextAttemptAt},${options.expiresAt},${this.sql.json(poll as never)},${now},${now}) on conflict (proof_id) do update set proof_id=excluded.proof_id returning payload`;return inserted[0]?.payload??poll;
  }
  async recoverMissingPolls(options:{nextAttemptAt:string;expiresAt:string;maxAttempts:number;limit:number}){const rows=await this.sql<{workspace_id:string;content_item_id:string;proof_id:string}[]>`select p.workspace_id,p.content_item_id,p.id as proof_id from publish_proofs p left join instagram_collaborator_polls cp on cp.proof_id=p.id where p.platform='instagram' and p.payload->'collaboratorInviteProof'->>'requestState'='requested_unverified' and cp.proof_id is null order by p.published_at,p.id limit ${options.limit}`;let recovered=0;for(const row of rows)if(await this.createPollFromStoredProof(row.workspace_id,row.content_item_id,row.proof_id,options))recovered+=1;return recovered;}
  async claimDuePolls(owner:string,_now:string,limit:number,leaseSeconds:number){return this.sql.begin(async(sql)=>{const rows=await sql<PollRow[]>`select payload from instagram_collaborator_polls where status in ('pending','processing','unavailable') and next_attempt_at<=clock_timestamp() and expires_at>clock_timestamp() and attempt_count<max_attempts and (claim_lease_expires_at is null or claim_lease_expires_at<=clock_timestamp()) order by next_attempt_at,proof_id limit ${limit} for update skip locked`;const result:InstagramCollaboratorPoll[]=[];for(const row of rows){const claimId=`${owner}:${randomUUID()}`;const updatedAt=new Date().toISOString();const next={...row.payload,status:"processing" as const,attemptCount:row.payload.attemptCount+1,claimId,updatedAt};await sql`update instagram_collaborator_polls set status='processing',attempt_count=${next.attemptCount},active_claim_id=${claimId},claim_lease_expires_at=clock_timestamp()+(${leaseSeconds}::text||' seconds')::interval,payload=${sql.json(next as never)},updated_at=clock_timestamp() where proof_id=${next.proofId}`;result.push(next);}return result;});}
  async recordPollResult(poll:InstagramCollaboratorPoll,result:{snapshots:CurrentCollaboratorStatusSnapshot[];providerReadComplete:boolean;trackingComplete:boolean;availability:string;capturedAt:string;rawResponseSha256?:string;retryAt?:string;errorSummary?:string}){await this.sql.begin(async(sql)=>{if(!poll.claimId)throw new DomainError("This collaborator status lease is stale.","instagram_collaborator_poll_lease_lost",409);const fenced=await sql<{proof_id:string}[]>`select proof_id from instagram_collaborator_polls where proof_id=${poll.proofId} and workspace_id=${poll.workspaceId} and status='processing' and active_claim_id=${poll.claimId} and claim_lease_expires_at>clock_timestamp() limit 1 for update`;if(!fenced[0])throw new DomainError("This collaborator status lease is stale.","instagram_collaborator_poll_lease_lost",409);this.validateSnapshots(poll,result.snapshots,result.providerReadComplete);const expired=!result.trackingComplete&&(!result.retryAt||poll.attemptCount>=poll.maxAttempts||result.retryAt>=poll.expiresAt);const status=result.trackingComplete?"complete":expired?"expired":result.availability==="available"?"pending":"unavailable";const {claimId:_,claimLeaseExpiresAt:__,...withoutClaim}=poll;const next={...withoutClaim,status:status as InstagramCollaboratorPoll["status"],nextAttemptAt:result.retryAt??poll.nextAttemptAt,availability:result.availability,capturedAt:result.capturedAt,latestReadComplete:result.providerReadComplete,...(result.rawResponseSha256?{rawResponseSha256:result.rawResponseSha256}:{}),...(result.errorSummary?{errorSummary:result.errorSummary}:{}),updatedAt:result.capturedAt};for(const snapshot of result.snapshots){await sql`insert into instagram_collaborator_status_snapshots (workspace_id,brand_id,content_item_id,proof_id,account_id,external_media_id,requested_usernames_sha256,username,status,captured_at,provider_response_sha256,payload) values (${snapshot.workspaceId},${snapshot.brandId},${snapshot.contentItemId},${snapshot.proofId},${snapshot.accountId},${snapshot.externalMediaId},${snapshot.requestedUsernamesSha256},${snapshot.username},${snapshot.status},${snapshot.capturedAt},${snapshot.providerResponseSha256},${sql.json(snapshot as never)}) on conflict (workspace_id,proof_id,username) do update set status=excluded.status,captured_at=excluded.captured_at,provider_response_sha256=excluded.provider_response_sha256,payload=excluded.payload`;}
      await sql`update instagram_collaborator_polls set status=${status},next_attempt_at=${next.nextAttemptAt},availability=${result.availability},error_summary=${result.errorSummary??null},captured_at=${result.capturedAt},latest_read_complete=${result.providerReadComplete},raw_response_sha256=${result.rawResponseSha256??null},active_claim_id=null,claim_lease_expires_at=null,payload=${sql.json(next as never)},updated_at=clock_timestamp() where proof_id=${poll.proofId} and workspace_id=${poll.workspaceId} and active_claim_id=${poll.claimId}`;});}
  private validateSnapshots(poll:InstagramCollaboratorPoll,snapshots:CurrentCollaboratorStatusSnapshot[],providerReadComplete:boolean){const requested=new Set(poll.inviteProof.requestedUsernames);const seen=new Set<string>();for(const snapshot of snapshots){if(seen.has(snapshot.username)||!requested.has(snapshot.username)||snapshot.workspaceId!==poll.workspaceId||snapshot.brandId!==poll.brandId||snapshot.contentItemId!==poll.contentItemId||snapshot.proofId!==poll.proofId||snapshot.accountId!==poll.accountId||snapshot.externalMediaId!==poll.externalMediaId||snapshot.requestedUsernamesSha256!==poll.inviteProof.requestedUsernamesSha256)throw new Error("Instagram collaborator snapshot lineage mismatch.");seen.add(snapshot.username);}if(providerReadComplete&&(seen.size!==requested.size||[...requested].some((username)=>!seen.has(username))))throw new Error("A complete collaborator provider read must include each requested username exactly once.");}
  async getStatus(workspaceId:string,contentItemId:string,proofId:string):Promise<InstagramCollaboratorStatusView>{const polls=await this.sql<PollRow[]>`select payload from instagram_collaborator_polls where proof_id=${proofId} and workspace_id=${workspaceId} and content_item_id=${contentItemId} limit 1`;if(!polls[0])return{poll:null,snapshots:[]};const {claimId:_,claimLeaseExpiresAt:__,...safePoll}=polls[0].payload;const rows=await this.sql<SnapshotRow[]>`select payload from instagram_collaborator_status_snapshots where workspace_id=${workspaceId} and content_item_id=${contentItemId} and proof_id=${proofId} order by username`;return{poll:safePoll,snapshots:rows.map((row)=>row.payload)};}
}
