import type { AuditEvent, AutomationApiKey, AutomationDeliveryStatus, AutomationEvent, AutomationImportRow, AutomationImportSession, AutomationRepository, AutomationWebhookDelivery, AutomationWebhookSubscription } from "@originpost/domain";
import type { Sql, TransactionSql } from "postgres";

type KeyRow = { id: string; workspace_id: string; name: string; key_prefix: string; secret_hash: string; scopes: AutomationApiKey["scopes"]; brand_ids: string[]; account_ids: string[]; created_by: string; created_at: Date; expires_at: Date | null; last_used_at: Date | null; revoked_at: Date | null };
type SubscriptionRow = { id: string; workspace_id: string; name: string; url: string; topics: AutomationWebhookSubscription["topics"]; brand_ids: string[]; secret: AutomationWebhookSubscription["secret"]; active: boolean; created_by: string; created_at: Date; updated_at: Date; disabled_at: Date | null };
type EventRow = { id: string; workspace_id: string; brand_id: string | null; topic: AutomationEvent["topic"]; content_item_id: string | null; aggregate_version: number | null; occurred_at: Date; actor_type: AuditEvent["actorType"]; payload: Record<string, unknown> };
type DeliveryRow = { id: string; workspace_id: string; subscription_id: string; event_id: string; status: AutomationDeliveryStatus; attempts: number; available_at: Date; lease_owner: string | null; lease_expires_at: Date | null; response_status: number | null; response_sha256: string | null; last_error: string | null; delivered_at: Date | null; created_at: Date; updated_at: Date };
type ImportRow = { id: string; workspace_id: string; api_key_id: string; brand_id: string; format: AutomationImportSession["format"]; source_sha256: string; status: AutomationImportSession["status"]; rows: AutomationImportRow[]; failure_reason: string | null; created_at: Date; updated_at: Date; committed_at: Date | null };

const iso = (value: Date) => value.toISOString();
function key(row: KeyRow): AutomationApiKey { return { id: row.id, workspaceId: row.workspace_id, name: row.name, keyPrefix: row.key_prefix, secretHash: row.secret_hash, scopes: row.scopes, brandIds: row.brand_ids, accountIds: row.account_ids, createdBy: row.created_by, createdAt: iso(row.created_at), ...(row.expires_at ? { expiresAt: iso(row.expires_at) } : {}), ...(row.last_used_at ? { lastUsedAt: iso(row.last_used_at) } : {}), ...(row.revoked_at ? { revokedAt: iso(row.revoked_at) } : {}) } }
function subscription(row: SubscriptionRow): AutomationWebhookSubscription { return { id: row.id, workspaceId: row.workspace_id, name: row.name, url: row.url, topics: row.topics, brandIds: row.brand_ids, secret: row.secret, active: row.active, createdBy: row.created_by, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at), ...(row.disabled_at ? { disabledAt: iso(row.disabled_at) } : {}) } }
function event(row: EventRow): AutomationEvent { return { id: row.id, workspaceId: row.workspace_id, ...(row.brand_id ? { brandId: row.brand_id } : {}), topic: row.topic, ...(row.content_item_id ? { contentItemId: row.content_item_id } : {}), ...(row.aggregate_version !== null ? { aggregateVersion: row.aggregate_version } : {}), occurredAt: iso(row.occurred_at), actorType: row.actor_type, payload: row.payload } }
function delivery(row: DeliveryRow): AutomationWebhookDelivery { return { id: row.id, workspaceId: row.workspace_id, subscriptionId: row.subscription_id, eventId: row.event_id, status: row.status, attempts: row.attempts, availableAt: iso(row.available_at), ...(row.lease_owner ? { leaseOwner: row.lease_owner } : {}), ...(row.lease_expires_at ? { leaseExpiresAt: iso(row.lease_expires_at) } : {}), ...(row.response_status !== null ? { responseStatus: row.response_status } : {}), ...(row.response_sha256 ? { responseSha256: row.response_sha256 } : {}), ...(row.last_error ? { lastError: row.last_error } : {}), ...(row.delivered_at ? { deliveredAt: iso(row.delivered_at) } : {}), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) } }
function importSession(row: ImportRow): AutomationImportSession { return { id: row.id, workspaceId: row.workspace_id, apiKeyId: row.api_key_id, brandId: row.brand_id, format: row.format, sourceSha256: row.source_sha256, status: row.status, rows: row.rows, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at), ...(row.committed_at ? { committedAt: iso(row.committed_at) } : {}), ...(row.failure_reason ? { failureReason: row.failure_reason } : {}) } }

async function audit(sql: Sql | TransactionSql, value: AuditEvent) {
  await sql`insert into audit_events (id, workspace_id, content_item_id, actor_id, actor_type, action, detail, created_at) values (${value.id}, ${value.workspaceId}, ${value.contentItemId ?? null}, ${value.actorId}, ${value.actorType}, ${value.action}, ${sql.json(value.detail as never)}, ${value.createdAt}) on conflict (id) do nothing`;
}

export class PostgresAutomationRepository implements AutomationRepository {
  constructor(private readonly sql: Sql) {}

  async saveApiKey(value: AutomationApiKey, auditEvent: AuditEvent): Promise<void> {
    await this.sql.begin(async (sql) => {
      await sql`insert into automation_api_keys (id, workspace_id, name, key_prefix, secret_hash, scopes, brand_ids, account_ids, created_by, created_at, expires_at, last_used_at, revoked_at) values (${value.id}, ${value.workspaceId}, ${value.name}, ${value.keyPrefix}, ${value.secretHash}, ${value.scopes}, ${value.brandIds}, ${value.accountIds}, ${value.createdBy}, ${value.createdAt}, ${value.expiresAt ?? null}, ${value.lastUsedAt ?? null}, ${value.revokedAt ?? null})`;
      await audit(sql, auditEvent);
    });
  }
  async listApiKeys(workspaceId: string): Promise<AutomationApiKey[]> { const rows = await this.sql<KeyRow[]>`select * from automation_api_keys where workspace_id = ${workspaceId} order by created_at desc`; return rows.map(key) }
  async getApiKey(workspaceId: string, id: string): Promise<AutomationApiKey | null> { const rows = await this.sql<KeyRow[]>`select * from automation_api_keys where workspace_id = ${workspaceId} and id = ${id} limit 1`; return rows[0] ? key(rows[0]) : null }
  async authenticateApiKey(secretHash: string, now: string): Promise<AutomationApiKey | null> { const rows = await this.sql<KeyRow[]>`select * from automation_api_keys where secret_hash = ${secretHash} and revoked_at is null and (expires_at is null or expires_at > ${now}) limit 1`; return rows[0] ? key(rows[0]) : null }
  async touchApiKey(id: string, lastUsedAt: string): Promise<void> { await this.sql`update automation_api_keys set last_used_at = ${lastUsedAt} where id = ${id} and revoked_at is null` }
  async revokeApiKey(workspaceId: string, id: string, revokedAt: string, auditEvent: AuditEvent): Promise<AutomationApiKey | null> {
    return this.sql.begin(async (sql) => { const rows = await sql<KeyRow[]>`update automation_api_keys set revoked_at = coalesce(revoked_at, ${revokedAt}) where workspace_id = ${workspaceId} and id = ${id} returning *`; if (!rows[0]) return null; await audit(sql, auditEvent); return key(rows[0]) });
  }

  async saveSubscription(value: AutomationWebhookSubscription, auditEvent: AuditEvent): Promise<void> {
    await this.sql.begin(async (sql) => {
      await sql`insert into automation_webhook_subscriptions (id, workspace_id, name, url, topics, brand_ids, secret, active, created_by, created_at, updated_at, disabled_at) values (${value.id}, ${value.workspaceId}, ${value.name}, ${value.url}, ${value.topics}, ${value.brandIds}, ${sql.json(value.secret as never)}, ${value.active}, ${value.createdBy}, ${value.createdAt}, ${value.updatedAt}, ${value.disabledAt ?? null})`;
      await audit(sql, auditEvent);
    });
  }
  async listSubscriptions(workspaceId: string): Promise<AutomationWebhookSubscription[]> { const rows = await this.sql<SubscriptionRow[]>`select * from automation_webhook_subscriptions where workspace_id = ${workspaceId} order by created_at desc`; return rows.map(subscription) }
  async getSubscription(workspaceId: string, id: string): Promise<AutomationWebhookSubscription | null> { const rows = await this.sql<SubscriptionRow[]>`select * from automation_webhook_subscriptions where workspace_id = ${workspaceId} and id = ${id} limit 1`; return rows[0] ? subscription(rows[0]) : null }
  async disableSubscription(workspaceId: string, id: string, disabledAt: string, auditEvent: AuditEvent): Promise<AutomationWebhookSubscription | null> {
    return this.sql.begin(async (sql) => { const rows = await sql<SubscriptionRow[]>`update automation_webhook_subscriptions set active = false, disabled_at = coalesce(disabled_at, ${disabledAt}), updated_at = ${disabledAt} where workspace_id = ${workspaceId} and id = ${id} returning *`; if (!rows[0]) return null; await sql`update automation_webhook_deliveries set status='dead_letter', last_error='Webhook subscription disabled.', lease_owner=null, lease_expires_at=null, updated_at=${disabledAt} where workspace_id=${workspaceId} and subscription_id=${id} and status in ('pending','processing','failed')`; await audit(sql, auditEvent); return subscription(rows[0]) });
  }

  async recordEvent(value: AutomationEvent): Promise<void> {
    await this.sql.begin(async (sql) => {
      const inserted = await sql<{ id: string }[]>`insert into automation_events (id, workspace_id, brand_id, topic, content_item_id, aggregate_version, occurred_at, actor_type, payload) values (${value.id}, ${value.workspaceId}, ${value.brandId ?? null}, ${value.topic}, ${value.contentItemId ?? null}, ${value.aggregateVersion ?? null}, ${value.occurredAt}, ${value.actorType}, ${sql.json(value.payload as never)}) on conflict (id) do nothing returning id`;
      if (!inserted.length) return;
      await sql`insert into automation_webhook_deliveries (id, workspace_id, subscription_id, event_id, status, attempts, available_at, created_at, updated_at) select ${"delivery_"} || md5(subscription.id || ':' || ${value.id}), ${value.workspaceId}, subscription.id, ${value.id}, 'pending', 0, ${value.occurredAt}, ${value.occurredAt}, ${value.occurredAt} from automation_webhook_subscriptions subscription where subscription.workspace_id = ${value.workspaceId} and subscription.active = true and ${value.topic} = any(subscription.topics) and (cardinality(subscription.brand_ids) = 0 or ${value.brandId ?? null} = any(subscription.brand_ids)) on conflict (subscription_id, event_id) do nothing`;
    });
  }
  async recordTestEvent(value: AutomationEvent, subscriptionId: string): Promise<void> { await this.sql.begin(async (sql) => { const inserted = await sql<{ id: string }[]>`insert into automation_events (id, workspace_id, brand_id, topic, content_item_id, aggregate_version, occurred_at, actor_type, payload) values (${value.id},${value.workspaceId},null,${value.topic},null,null,${value.occurredAt},${value.actorType},${sql.json(value.payload as never)}) on conflict (id) do nothing returning id`; if (!inserted.length) return; await sql`insert into automation_webhook_deliveries (id, workspace_id, subscription_id, event_id, status, attempts, available_at, created_at, updated_at) select ${"delivery_"} || md5(subscription.id || ':' || ${value.id}), ${value.workspaceId}, subscription.id, ${value.id}, 'pending', 0, ${value.occurredAt}, ${value.occurredAt}, ${value.occurredAt} from automation_webhook_subscriptions subscription where subscription.id=${subscriptionId} and subscription.workspace_id=${value.workspaceId} and subscription.active=true on conflict (subscription_id,event_id) do nothing` }) }
  async recordEventFromAudit(): Promise<void> { /* PostgreSQL trigger captures audit events atomically. */ }
  async listEvents(workspaceId: string, limit = 100): Promise<AutomationEvent[]> { const rows = await this.sql<EventRow[]>`select * from automation_events where workspace_id = ${workspaceId} order by occurred_at desc, id desc limit ${Math.max(1, Math.min(limit, 200))}`; return rows.map(event) }
  async listDeliveries(workspaceId: string, limit = 100): Promise<AutomationWebhookDelivery[]> { const rows = await this.sql<DeliveryRow[]>`select * from automation_webhook_deliveries where workspace_id = ${workspaceId} order by created_at desc, id desc limit ${Math.max(1, Math.min(limit, 200))}`; return rows.map(delivery) }
  async deliveryStatusSummary(workspaceId: string) {
    const counts = await this.sql<{ status: AutomationDeliveryStatus; count: number }[]>`select status, count(*)::int as count from automation_webhook_deliveries where workspace_id = ${workspaceId} group by status`;
    const latest = await this.sql<{ id: string; updated_at: Date }[]>`select id, updated_at from automation_webhook_deliveries where workspace_id = ${workspaceId} and status = 'dead_letter' order by updated_at desc, id desc limit 1`;
    return {
      counts: Object.fromEntries(counts.map((entry) => [entry.status, entry.count])) as Partial<Record<AutomationDeliveryStatus, number>>,
      ...(latest[0] ? { latestDeadLetterId: latest[0].id, latestDeadLetterAt: latest[0].updated_at.toISOString() } : {}),
    };
  }
  async getDelivery(id: string) {
    const rows = await this.sql<(DeliveryRow & { event_row: EventRow; subscription_row: SubscriptionRow })[]>`select delivery.*, to_jsonb(event.*) as event_row, to_jsonb(subscription.*) as subscription_row from automation_webhook_deliveries delivery join automation_events event on event.id = delivery.event_id join automation_webhook_subscriptions subscription on subscription.id = delivery.subscription_id where delivery.id = ${id} limit 1`;
    const row = rows[0]; if (!row) return null;
    const eventRow = row.event_row as unknown as EventRow; const subscriptionRow = row.subscription_row as unknown as SubscriptionRow;
    for (const field of ["occurred_at"] as const) if (typeof eventRow[field] === "string") eventRow[field] = new Date(eventRow[field]) as never;
    for (const field of ["created_at", "updated_at", "disabled_at"] as const) if (typeof subscriptionRow[field] === "string") subscriptionRow[field] = new Date(subscriptionRow[field] as string) as never;
    return { delivery: delivery(row), event: event(eventRow), subscription: subscription(subscriptionRow) };
  }
  async claimDeliveries(owner: string, now: string, limit = 20, leaseSeconds = 60): Promise<AutomationWebhookDelivery[]> {
    const rows = await this.sql<DeliveryRow[]>`with due as (select id from automation_webhook_deliveries where available_at <= ${now} and (status in ('pending','failed') or (status = 'processing' and lease_expires_at <= ${now})) order by available_at, id for update skip locked limit ${Math.max(1, Math.min(limit, 100))}) update automation_webhook_deliveries delivery set status='processing', attempts=delivery.attempts+1, lease_owner=${owner}, lease_expires_at=${now}::timestamptz + (${leaseSeconds}::text || ' seconds')::interval, updated_at=${now} from due where delivery.id=due.id returning delivery.*`;
    return rows.map(delivery);
  }
  async completeDelivery(id: string, owner: string, responseStatus: number, responseSha256: string, completedAt: string): Promise<void> { await this.sql`update automation_webhook_deliveries set status='delivered', response_status=${responseStatus}, response_sha256=${responseSha256}, delivered_at=${completedAt}, updated_at=${completedAt}, lease_owner=null, lease_expires_at=null, last_error=null where id=${id} and status='processing' and lease_owner=${owner}` }
  async failDelivery(id: string, owner: string, error: string, retryAt: string, failedAt: string, maxAttempts = 8): Promise<void> { await this.sql`update automation_webhook_deliveries set status=case when attempts >= ${maxAttempts} then 'dead_letter' else 'failed' end, last_error=${error.slice(0,500)}, available_at=${retryAt}, updated_at=${failedAt}, lease_owner=null, lease_expires_at=null where id=${id} and status='processing' and lease_owner=${owner}` }
  async retryDelivery(workspaceId: string, id: string, retryAt: string): Promise<boolean> { const rows = await this.sql<{ id: string }[]>`update automation_webhook_deliveries set status='pending', available_at=${retryAt}, updated_at=${retryAt}, last_error=null where workspace_id=${workspaceId} and id=${id} and status in ('failed','dead_letter') returning id`; return rows.length === 1 }
  async saveImportSession(value: AutomationImportSession): Promise<void> { await this.sql`insert into automation_import_sessions (id, workspace_id, api_key_id, brand_id, format, source_sha256, status, rows, failure_reason, created_at, updated_at, committed_at) values (${value.id},${value.workspaceId},${value.apiKeyId},${value.brandId},${value.format},${value.sourceSha256},${value.status},${this.sql.json(value.rows as never)},${value.failureReason ?? null},${value.createdAt},${value.updatedAt},${value.committedAt ?? null}) on conflict (workspace_id, api_key_id, source_sha256) do nothing` }
  async getImportSession(workspaceId: string, id: string): Promise<AutomationImportSession | null> { const rows = await this.sql<ImportRow[]>`select * from automation_import_sessions where workspace_id=${workspaceId} and id=${id} limit 1`; return rows[0] ? importSession(rows[0]) : null }
  async claimImportSession(workspaceId: string, id: string, apiKeyId: string, claimedAt: string, staleBefore: string): Promise<AutomationImportSession | null> { const rows = await this.sql<ImportRow[]>`update automation_import_sessions set status='processing', updated_at=${claimedAt}, failure_reason=null where workspace_id=${workspaceId} and id=${id} and api_key_id=${apiKeyId} and (status='staged' or (status='processing' and updated_at <= ${staleBefore})) returning *`; return rows[0] ? importSession(rows[0]) : null }
  async completeImportSession(workspaceId: string, id: string, rowsValue: AutomationImportRow[], completedAt: string): Promise<AutomationImportSession | null> { const rows = await this.sql<ImportRow[]>`update automation_import_sessions set status='committed', rows=${this.sql.json(rowsValue as never)}, committed_at=${completedAt}, updated_at=${completedAt}, failure_reason=null where workspace_id=${workspaceId} and id=${id} and status='processing' returning *`; return rows[0] ? importSession(rows[0]) : null }
  async failImportSession(workspaceId: string, id: string, reason: string, failedAt: string): Promise<void> { await this.sql`update automation_import_sessions set status='failed', failure_reason=${reason.slice(0,500)}, updated_at=${failedAt} where workspace_id=${workspaceId} and id=${id} and status='processing'` }
}
