import type { AuditEvent, BatchPlan, BatchPlanRepository } from "@originpost/domain";
import type { Sql, TransactionSql } from "postgres";

type BatchRow = { id: string; workspace_id: string; brand_id: string; version: number; name: string; source_sha256: string; status: BatchPlan["status"]; rows: BatchPlan["rows"]; created_by: string; created_at: Date; updated_at: Date; committed_at: Date | null; archived_at: Date | null };
const iso = (value: Date) => value.toISOString();
function plan(row: BatchRow): BatchPlan { return { id: row.id, workspaceId: row.workspace_id, brandId: row.brand_id, version: row.version, name: row.name, sourceSha256: row.source_sha256, status: row.status, rows: row.rows, createdBy: row.created_by, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at), ...(row.committed_at ? { committedAt: iso(row.committed_at) } : {}), ...(row.archived_at ? { archivedAt: iso(row.archived_at) } : {}) }; }
async function audit(sql: Sql | TransactionSql, value: AuditEvent) { await sql`insert into audit_events (id, workspace_id, content_item_id, actor_id, actor_type, action, detail, created_at) values (${value.id},${value.workspaceId},${value.contentItemId ?? null},${value.actorId},${value.actorType},${value.action},${sql.json(value.detail as never)},${value.createdAt}) on conflict (id) do nothing`; }

export class PostgresBatchPlanRepository implements BatchPlanRepository {
  constructor(private readonly sql: Sql) {}
  async create(value: BatchPlan, event: AuditEvent): Promise<{ plan: BatchPlan; created: boolean }> { return this.sql.begin(async (sql) => { const inserted = await sql<BatchRow[]>`insert into batch_operation_plans (id,workspace_id,brand_id,version,name,source_sha256,status,rows,created_by,created_at,updated_at,committed_at,archived_at) values (${value.id},${value.workspaceId},${value.brandId},${value.version},${value.name},${value.sourceSha256},${value.status},${sql.json(value.rows as never)},${value.createdBy},${value.createdAt},${value.updatedAt},${value.committedAt ?? null},${value.archivedAt ?? null}) on conflict (workspace_id,brand_id,source_sha256) do nothing returning *`; if (inserted[0]) { await audit(sql,event); return { plan: plan(inserted[0]), created: true }; } const existing = await sql<BatchRow[]>`select * from batch_operation_plans where workspace_id=${value.workspaceId} and brand_id=${value.brandId} and source_sha256=${value.sourceSha256} limit 1`; if (!existing[0]) throw new Error("Batch plan conflict could not be read."); return { plan: plan(existing[0]), created: false }; }); }
  async list(workspaceId: string, brandId?: string, limit = 50): Promise<BatchPlan[]> { const rows = brandId ? await this.sql<BatchRow[]>`select * from batch_operation_plans where workspace_id=${workspaceId} and brand_id=${brandId} order by created_at desc,id desc limit ${Math.max(1,Math.min(limit,100))}` : await this.sql<BatchRow[]>`select * from batch_operation_plans where workspace_id=${workspaceId} order by created_at desc,id desc limit ${Math.max(1,Math.min(limit,100))}`; return rows.map(plan); }
  async get(workspaceId: string, id: string): Promise<BatchPlan | null> { const rows = await this.sql<BatchRow[]>`select * from batch_operation_plans where workspace_id=${workspaceId} and id=${id} limit 1`; return rows[0] ? plan(rows[0]) : null; }
  async replace(workspaceId: string, id: string, expectedVersion: number, value: BatchPlan, event: AuditEvent): Promise<BatchPlan | null> { return this.sql.begin(async (sql) => { const rows = await sql<BatchRow[]>`update batch_operation_plans set version=${value.version},status=${value.status},rows=${sql.json(value.rows as never)},updated_at=${value.updatedAt},committed_at=${value.committedAt ?? null},archived_at=${value.archivedAt ?? null} where workspace_id=${workspaceId} and id=${id} and version=${expectedVersion} returning *`; if (!rows[0]) return null; await audit(sql,event); return plan(rows[0]); }); }
}
