import { DomainError, type AgentRunLedgerEntry, type AgentRuntimeAssignment, type AgentRuntimeCredential, type AgentRuntimeExecutionContext, type AgentRuntimeProfile, type AgentRuntimeRepository, type AuditEvent } from "@originpost/domain";
import type { Sql, TransactionSql } from "postgres";

type ProfileRow={payload:AgentRuntimeProfile;credential_key_version:string|null;credential_algorithm:string|null;credential_iv:string|null;credential_auth_tag:string|null;credential_ciphertext:string|null};
type AssignmentRow={workspace_id:string;brand_id:string;profile_id:string;assigned_by:string;assigned_at:Date|string};
type RunRow={payload:AgentRunLedgerEntry};
const iso=(value:Date|string)=>value instanceof Date?value.toISOString():new Date(value).toISOString();
async function audit(sql:Sql|TransactionSql,event:AuditEvent){await sql`insert into audit_events(id,workspace_id,content_item_id,actor_id,actor_type,action,detail,created_at) values(${event.id},${event.workspaceId},${event.contentItemId??null},${event.actorId},${event.actorType},${event.action},${sql.json(event.detail as never)},${event.createdAt}) on conflict(id) do nothing`;}
const secret=(row:ProfileRow):AgentRuntimeCredential|null=>row.credential_ciphertext?{keyVersion:"v1",algorithm:"aes-256-gcm",iv:row.credential_iv!,authTag:row.credential_auth_tag!,ciphertext:row.credential_ciphertext}:null;

export class PostgresAgentRuntimeRepository implements AgentRuntimeRepository{
  constructor(private readonly sql:Sql){}
  async listProfiles(workspaceId:string){const rows=await this.sql<ProfileRow[]>`select payload,credential_key_version,credential_algorithm,credential_iv,credential_auth_tag,credential_ciphertext from agent_runtime_profiles where workspace_id=${workspaceId} order by name,id`;return rows.map((row)=>row.payload);}
  async getProfile(workspaceId:string,id:string){const rows=await this.sql<ProfileRow[]>`select payload,credential_key_version,credential_algorithm,credential_iv,credential_auth_tag,credential_ciphertext from agent_runtime_profiles where workspace_id=${workspaceId} and id=${id} limit 1`;return rows[0]?.payload??null;}
  async createProfile(profile:AgentRuntimeProfile,credential:AgentRuntimeCredential|null,event:AuditEvent){await this.sql.begin(async(sql)=>{const saved=await sql<{id:string}[]>`insert into agent_runtime_profiles(id,workspace_id,version,name,preset,base_url,text_model,credential_configured,status,credential_key_version,credential_algorithm,credential_iv,credential_auth_tag,credential_ciphertext,payload,created_by,created_at,updated_at) values(${profile.id},${profile.workspaceId},${profile.version},${profile.name},${profile.preset},${profile.baseUrl},${profile.textModel},${profile.credentialConfigured},${profile.status},${credential?.keyVersion??null},${credential?.algorithm??null},${credential?.iv??null},${credential?.authTag??null},${credential?.ciphertext??null},${sql.json(profile as never)},${profile.createdBy},${profile.createdAt},${profile.updatedAt}) on conflict do nothing returning id`;if(!saved[0])throw new DomainError("AI runtime already exists.","agent_runtime_exists",409);await audit(sql,event);});}
  async updateProfile(profile:AgentRuntimeProfile,expectedVersion:number,credential:AgentRuntimeCredential|undefined,event:AuditEvent){return this.sql.begin(async(sql)=>{const current=await sql<ProfileRow[]>`select payload,credential_key_version,credential_algorithm,credential_iv,credential_auth_tag,credential_ciphertext from agent_runtime_profiles where workspace_id=${profile.workspaceId} and id=${profile.id} and version=${expectedVersion} for update`;if(!current[0])return null;const nextSecret=credential===undefined?secret(current[0]):credential;const changed=await sql<{id:string}[]>`update agent_runtime_profiles set version=${profile.version},name=${profile.name},base_url=${profile.baseUrl},text_model=${profile.textModel},credential_configured=${profile.credentialConfigured},status=${profile.status},credential_key_version=${nextSecret?.keyVersion??null},credential_algorithm=${nextSecret?.algorithm??null},credential_iv=${nextSecret?.iv??null},credential_auth_tag=${nextSecret?.authTag??null},credential_ciphertext=${nextSecret?.ciphertext??null},payload=${sql.json(profile as never)},updated_at=${profile.updatedAt} where workspace_id=${profile.workspaceId} and id=${profile.id} and version=${expectedVersion} returning id`;if(!changed[0])return null;await audit(sql,event);return profile;});}
  async removeProfile(workspaceId:string,id:string,expectedVersion:number,event:AuditEvent){return this.sql.begin(async(sql)=>{const rows=await sql<{id:string}[]>`delete from agent_runtime_profiles where workspace_id=${workspaceId} and id=${id} and version=${expectedVersion} returning id`;if(!rows[0])return false;await audit(sql,event);return true;});}
  async updateHealth(workspaceId:string,id:string,expectedVersion:number,input:{status:"healthy"|"error";checkedAt:string;error?:string},event:AuditEvent){return this.sql.begin(async(sql)=>{const rows=await sql<ProfileRow[]>`select payload,credential_key_version,credential_algorithm,credential_iv,credential_auth_tag,credential_ciphertext from agent_runtime_profiles where workspace_id=${workspaceId} and id=${id} and version=${expectedVersion} for update`;const current=rows[0]?.payload;if(!current)return null;const next:AgentRuntimeProfile={...current,version:current.version+1,status:input.status,lastCheckedAt:input.checkedAt,updatedAt:input.checkedAt,...(input.error?{lastError:input.error}:{})};if(!input.error)delete next.lastError;const changed=await sql<{id:string}[]>`update agent_runtime_profiles set version=${next.version},status=${next.status},payload=${sql.json(next as never)},updated_at=${next.updatedAt} where workspace_id=${workspaceId} and id=${id} and version=${expectedVersion} returning id`;if(!changed[0])return null;await audit(sql,event);return next;});}
  async assign(value:AgentRuntimeAssignment,event:AuditEvent){await this.sql.begin(async(sql)=>{const profiles=await sql<{id:string}[]>`select id from agent_runtime_profiles where workspace_id=${value.workspaceId} and id=${value.profileId} and status='healthy'`;if(!profiles[0])throw new DomainError("Test this AI runtime before assigning it.","agent_runtime_not_ready",409);await sql`insert into agent_runtime_assignments(workspace_id,brand_id,profile_id,assigned_by,assigned_at) values(${value.workspaceId},${value.brandId},${value.profileId},${value.assignedBy},${value.assignedAt}) on conflict(workspace_id,brand_id) do update set profile_id=excluded.profile_id,assigned_by=excluded.assigned_by,assigned_at=excluded.assigned_at`;await audit(sql,event);});}
  async unassign(workspaceId:string,brandId:string,event:AuditEvent){return this.sql.begin(async(sql)=>{const rows=await sql<{brand_id:string}[]>`delete from agent_runtime_assignments where workspace_id=${workspaceId} and brand_id=${brandId} returning brand_id`;if(!rows[0])return false;await audit(sql,event);return true;});}
  async getAssignment(workspaceId:string,brandId:string){const rows=await this.sql<AssignmentRow[]>`select * from agent_runtime_assignments where workspace_id=${workspaceId} and brand_id=${brandId} limit 1`;const row=rows[0];return row?{workspaceId:row.workspace_id,brandId:row.brand_id,profileId:row.profile_id,assignedBy:row.assigned_by,assignedAt:iso(row.assigned_at)}:null;}
  async getProfileExecutionContext(workspaceId:string,profileId:string):Promise<AgentRuntimeExecutionContext|null>{const rows=await this.sql<ProfileRow[]>`select payload,credential_key_version,credential_algorithm,credential_iv,credential_auth_tag,credential_ciphertext from agent_runtime_profiles where workspace_id=${workspaceId} and id=${profileId} limit 1`;return rows[0]?{profile:rows[0].payload,credential:secret(rows[0])}:null;}
  async getExecutionContext(workspaceId:string,brandId:string):Promise<AgentRuntimeExecutionContext|null>{const rows=await this.sql<ProfileRow[]>`select p.payload,p.credential_key_version,p.credential_algorithm,p.credential_iv,p.credential_auth_tag,p.credential_ciphertext from agent_runtime_assignments a join agent_runtime_profiles p on p.workspace_id=a.workspace_id and p.id=a.profile_id where a.workspace_id=${workspaceId} and a.brand_id=${brandId} and p.status='healthy' limit 1`;return rows[0]?{profile:rows[0].payload,credential:secret(rows[0])}:null;}
  async recordRun(run:AgentRunLedgerEntry,event:AuditEvent){await this.sql.begin(async(sql)=>{await sql`insert into agent_run_ledger(id,workspace_id,brand_id,profile_id,content_item_id,feature,model,status,request_sha256,response_sha256,input_tokens,output_tokens,latency_ms,error_code,created_by,created_at,payload) values(${run.id},${run.workspaceId},${run.brandId},${run.profileId},${run.contentItemId??null},${run.feature},${run.model},${run.status},${run.requestSha256},${run.responseSha256??null},${run.inputTokens??null},${run.outputTokens??null},${run.latencyMs},${run.errorCode??null},${run.createdBy},${run.createdAt},${sql.json(run as never)})`;await audit(sql,event);});}
  async listRuns(workspaceId:string,profileId?:string,limit=100){const rows=await this.sql<RunRow[]>`select payload from agent_run_ledger where workspace_id=${workspaceId} and (${profileId??null}::text is null or profile_id=${profileId??null}) order by created_at desc limit ${Math.max(1,Math.min(200,limit))}`;return rows.map((row)=>row.payload);}
}
