import { ForbiddenException, Inject, Injectable } from "@nestjs/common";
import { can, createEvergreenEntry, evergreenAutoBlockers, evergreenFreshnessFlags, DomainError, type Actor, type AuditEvent, type EvergreenCandidate } from "@originpost/domain";
import { randomUUID } from "node:crypto";
import { INFRASTRUCTURE } from "../common/tokens.js";
import type { OriginPostInfrastructure } from "../infrastructure/infrastructure.types.js";
import type { CreateEvergreenPolicyDto, EvergreenQueryDto } from "./dto/evergreen.dto.js";

@Injectable()
export class EvergreenService {
  constructor(@Inject(INFRASTRUCTURE) private readonly infrastructure:OriginPostInfrastructure){}
  private readable(actor:Actor){if(!can(actor.role,"content:read"))throw new ForbiddenException("You cannot view the reuse queue.");}
  async summary(workspaceId:string,brandId:string|undefined,actor:Actor){this.readable(actor);const entries=await this.infrastructure.evergreenRepository.list({workspaceId,...(brandId?{brandId}:{}),limit:200});return {active:entries.filter((entry)=>entry.status==="active").length,paused:entries.filter((entry)=>entry.status==="paused").length,completed:entries.filter((entry)=>entry.status==="completed").length,needsReview:(await Promise.all(entries.map((entry)=>this.infrastructure.evergreenRepository.listOccurrences(workspaceId,entry.id,100)))).flat().filter((row)=>row.status==="review_ready").length};}
  async candidates(workspaceId:string,brandId:string|undefined,actor:Actor):Promise<EvergreenCandidate[]>{this.readable(actor);const items=await this.infrastructure.repository.list(workspaceId,brandId);const snapshots=await this.infrastructure.analyticsRepository.list(workspaceId,{...(brandId?{brandId}:{}),limit:2000});const candidates:EvergreenCandidate[]=[];for(const item of items.filter((value)=>value.status==="published")){for(const proof of item.proofs){const target=item.targets.findLast((value)=>value.platform===proof.platform&&value.accountId===proof.accountId&&value.draftId===proof.draftId&&value.status==="published");if(!target)continue;const snapshot=snapshots.filter((value)=>value.proofId===proof.id&&value.status==="ready").sort((a,b)=>b.capturedAt.localeCompare(a.capturedAt))[0];const preferred=snapshot?.metrics.find((metric)=>["views","reach","engaged_views"].includes(metric.key));const blockers=[...evergreenFreshnessFlags(item),...evergreenAutoBlockers(item,proof,target)];candidates.push({contentItemId:item.id,proofId:proof.id,title:item.title,platform:proof.platform,accountId:proof.accountId,publishedAt:proof.publishedAt,...(preferred?{metricLabel:preferred.key.replaceAll("_"," "),metricValue:preferred.value}:{}),autoEligible:false,blockers:[...new Set([...blockers,...(!snapshot?["Performance data is not available; choose it manually."]:[])])]});}}return candidates.sort((a,b)=>(b.metricValue??-1)-(a.metricValue??-1)||b.publishedAt.localeCompare(a.publishedAt));}
  async list(workspaceId:string,query:EvergreenQueryDto,actor:Actor){this.readable(actor);return this.infrastructure.evergreenRepository.list({workspaceId,...(query.brandId?{brandId:query.brandId}:{}),...(query.status?{status:query.status}:{}),limit:query.limit});}
  async get(workspaceId:string,id:string,actor:Actor){this.readable(actor);const entry=await this.infrastructure.evergreenRepository.get(workspaceId,id);if(!entry)throw new DomainError("Reuse cycle not found.","evergreen_not_found",404);return {entry,occurrences:await this.infrastructure.evergreenRepository.listOccurrences(workspaceId,id)};}
  async create(workspaceId:string,dto:CreateEvergreenPolicyDto,actor:Actor){const source=await this.infrastructure.repository.get(workspaceId,dto.sourceContentItemId);if(!source||source.brandId!==dto.brandId)throw new DomainError("Published source post not found in this brand.","evergreen_source_not_found",404);const existing=await this.infrastructure.evergreenRepository.list({workspaceId,brandId:dto.brandId,limit:200});if(existing.some((entry)=>entry.sourceProofId===dto.sourceProofId&&entry.status!=="completed"))throw new DomainError("This proof already has an active or paused reuse cycle.","evergreen_exists",409);const analytics=await this.infrastructure.analyticsRepository.latestForProof(workspaceId,dto.sourceProofId);if((!analytics||analytics.status!=="ready")&&!dto.manualReason?.trim())throw new DomainError("Add a short reason when performance data is unavailable.","evergreen_manual_reason_required",409);const result=createEvergreenEntry({source,proofId:dto.sourceProofId,name:dto.name,mode:dto.mode,intervalDays:dto.intervalDays,timezone:dto.timezone,firstPublishAt:dto.firstPublishAt,endAt:dto.endAt,maxOccurrences:dto.maxOccurrences,...(dto.manualReason?{manualReason:dto.manualReason}:{}),actor});const account=await this.infrastructure.connectedAccountRepository.get(workspaceId,result.entry.accountId);if(!account||account.brandId!==source.brandId||account.platform!==result.entry.platform||account.status!=="healthy")throw new DomainError("Reconnect the exact publishing account before creating this reuse cycle.","evergreen_account_not_ready",409);const draft=source.drafts.find((value)=>value.id===result.entry.sourceDraftId)!;for(const mediaId of draft.mediaIds){const media=await this.infrastructure.mediaRepository.get(workspaceId,mediaId);if(!media||media.brandId!==source.brandId||media.status!=="ready"||!(["owned","cleared"] as const).includes(media.rights as "owned"|"cleared"))throw new DomainError("Every reused media file must still be ready and owned or cleared.","evergreen_media_not_reusable",409);}await this.infrastructure.evergreenRepository.save(result.entry,result.event);return result.entry;}
  async state(workspaceId:string,id:string,expectedVersion:number|undefined,action:"pause"|"resume",actor:Actor){if((actor.actorType&&actor.actorType!=="human")||!can(actor.role,"automation:manage"))throw new ForbiddenException("Only a manager or owner can change reuse cycles.");if(!expectedVersion)throw new DomainError("Use If-Match with the current reuse cycle version.","version_required",428);const current=await this.infrastructure.evergreenRepository.get(workspaceId,id);if(!current)throw new DomainError("Reuse cycle not found.","evergreen_not_found",404);const at=new Date().toISOString();const event:AuditEvent={id:`evt_${randomUUID()}`,workspaceId,contentItemId:current.sourceContentItemId,actorId:actor.id,actorType:"human",action:action==="pause"?"evergreen.paused":"evergreen.resumed",detail:{evergreenEntryId:id,expectedVersion},createdAt:at};const entry=await this.infrastructure.evergreenRepository.update({workspaceId,id,expectedVersion,action,actorId:actor.id,at,event});if(!entry)throw new DomainError("This reuse cycle changed. Refresh and try again.","version_conflict",409);return entry;}
}
