"use client";

import { Activity, Bot, CheckCircle2, CircleOff, Cpu, KeyRound, Loader2, PlugZap, RefreshCw, ShieldCheck, Trash2, TriangleAlert } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { apiFetch, type AuthView } from "../../lib/api-client";
import styles from "./agent-runtime-settings.module.css";

type RuntimePreset = "openai" | "openrouter" | "ollama" | "custom" | "codex-local";
type RuntimeStatus = "unverified" | "healthy" | "error" | "disabled";
type RuntimeProfile = { id:string; version:number; name:string; preset:RuntimePreset; baseUrl:string; textModel:string; visionModel?:string; credentialConfigured:boolean; status:RuntimeStatus; lastCheckedAt?:string; lastError?:string; updatedAt:string };
type RuntimeAssignment = { workspaceId:string; brandId:string; profileId:string; assignedAt:string };
type RuntimeRun = { id:string; profileId:string; contentItemId?:string; feature:"draft_assist"|"copy_review"|"image_review"; model:string; status:"succeeded"|"failed"; inputTokens?:number; outputTokens?:number; latencyMs:number; errorCode?:string; createdAt:string };
type RuntimeView = { profiles:RuntimeProfile[]; assignment:RuntimeAssignment|null; runs:RuntimeRun[]; serverHermes:{configured:boolean;fallbackOnlyWhenUnassigned:boolean} };

const emptyView:RuntimeView={profiles:[],assignment:null,runs:[],serverHermes:{configured:false,fallbackOnlyWhenUnassigned:true}};
const presetCopy:Record<RuntimePreset,{label:string;hint:string;baseUrl:string;modelPlaceholder:string}>={
  "codex-local":{label:"Local Codex",hint:"Writing and image review through your signed-in local Codex bridge",baseUrl:"Server-configured local bridge",modelPlaceholder:"Exact model configured on the bridge"},
  openai:{label:"OpenAI",hint:"OpenAI-hosted text models",baseUrl:"https://api.openai.com/v1",modelPlaceholder:"Your approved OpenAI model"},
  openrouter:{label:"OpenRouter",hint:"Use one key across supported model providers",baseUrl:"https://openrouter.ai/api/v1",modelPlaceholder:"provider/model-name"},
  ollama:{label:"Ollama",hint:"A trusted local OpenAI-compatible server",baseUrl:"http://host.docker.internal:11434/v1",modelPlaceholder:"Your installed Ollama model"},
  custom:{label:"Custom endpoint",hint:"vLLM, LM Studio, or another compatible server",baseUrl:"",modelPlaceholder:"Exact provider model ID"},
};

function message(body:unknown,fallback:string){if(!body||typeof body!=="object")return fallback;const value=(body as{message?:unknown}).message;return Array.isArray(value)?value.join(" "):typeof value==="string"?value:fallback;}
function stamp(value?:string){if(!value)return"Not checked";const date=new Date(value);return Number.isNaN(date.getTime())?"Time unavailable":new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(date);}
function statusCopy(status:RuntimeStatus){return status==="healthy"?"Ready":status==="unverified"?"Test required":status==="disabled"?"Disabled":"Needs attention";}

export function AgentRuntimeSettings({auth,workspaceId,brandId}:{auth:AuthView;workspaceId:string;brandId:string}){
  const [view,setView]=useState<RuntimeView>(emptyView);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [formOpen,setFormOpen]=useState(false);const [preset,setPreset]=useState<RuntimePreset>("openrouter");
  const role=auth.memberships.find((membership)=>membership.workspaceId===workspaceId)?.role??auth.memberships[0]?.role;const isOwner=role==="owner";
  const assigned=useMemo(()=>view.profiles.find((profile)=>profile.id===view.assignment?.profileId),[view.assignment?.profileId,view.profiles]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await apiFetch(`/v1/agent-runtimes?workspaceId=${encodeURIComponent(workspaceId)}&brandId=${encodeURIComponent(brandId)}&limit=50`,{cache:"no-store"},auth.csrfToken);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(message(body,"Could not load AI runtimes."));setView(body as RuntimeView);}catch(cause){setError(cause instanceof Error?cause.message:"Could not load AI runtimes.");}finally{setLoading(false);}},[auth.csrfToken,brandId,workspaceId]);
  useEffect(()=>{void load();},[load]);

  async function request(path:string,init:RequestInit,fallback:string){setError("");setNotice("");const response=await apiFetch(path,init,auth.csrfToken);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(message(body,fallback));return body;}
  async function saveVision(profile:RuntimeProfile,event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(`vision:${profile.id}`);try{await request(`/v1/agent-runtimes/${encodeURIComponent(profile.id)}?workspaceId=${encodeURIComponent(workspaceId)}`,{method:"PATCH",headers:{"content-type":"application/json","If-Match":String(profile.version)},body:JSON.stringify({visionModel:String(data.get("visionModel")??"").trim()})},"Could not save the vision model.");setNotice("Vision model saved. Test this runtime again before using it.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not save the vision model.");}finally{setBusy("");}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const target=event.currentTarget;const data=new FormData(target);setBusy("create");try{const body={workspaceId,name:String(data.get("name")??"").trim(),preset,textModel:String(data.get("textModel")??"").trim(),...(String(data.get("visionModel")??"").trim()?{visionModel:String(data.get("visionModel")).trim()}:{}),...(preset==="ollama"||preset==="custom"?{baseUrl:String(data.get("baseUrl")??"").trim()}:{}),...(String(data.get("apiKey")??"").trim()?{apiKey:String(data.get("apiKey")).trim()}:{})};await request("/v1/agent-runtimes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)},"Could not save this AI runtime.");target.reset();setFormOpen(false);setNotice("Runtime saved. Test it before assigning it to this brand.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not save this AI runtime.");}finally{setBusy("");}}
  async function test(profile:RuntimeProfile){setBusy(`test:${profile.id}`);try{const result=await request(`/v1/agent-runtimes/${encodeURIComponent(profile.id)}/test?workspaceId=${encodeURIComponent(workspaceId)}`,{method:"POST"},"Could not test this runtime.") as {ok?:boolean;error?:{message?:string}};setNotice(result.ok?`${profile.name} is ready.`:result.error?.message??`${profile.name} needs attention.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not test this runtime.");}finally{setBusy("");}}
  async function assign(profile:RuntimeProfile){setBusy(`assign:${profile.id}`);try{await request(`/v1/agent-runtimes/${encodeURIComponent(profile.id)}/assign`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId,brandId})},"Could not assign this runtime.");setNotice(`${profile.name} now handles draft assistance for this brand.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not assign this runtime.");}finally{setBusy("");}}
  async function unassign(){setBusy("unassign");try{await request(`/v1/agent-runtimes/assignments/${encodeURIComponent(brandId)}?workspaceId=${encodeURIComponent(workspaceId)}`,{method:"DELETE"},"Could not return this brand to the server default.");setNotice(view.serverHermes.configured?"This brand now uses the configured server draft provider.":"Assignment removed. Assign a tested runtime before drafting with AI.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not remove this assignment.");}finally{setBusy("");}}
  async function toggle(profile:RuntimeProfile){const disabled=profile.status!=="disabled";setBusy(`toggle:${profile.id}`);try{await request(`/v1/agent-runtimes/${encodeURIComponent(profile.id)}?workspaceId=${encodeURIComponent(workspaceId)}`,{method:"PATCH",headers:{"content-type":"application/json","if-match":String(profile.version)},body:JSON.stringify({disabled})},`Could not ${disabled?"disable":"enable"} this runtime.`);setNotice(disabled?`${profile.name} is disabled.`:`${profile.name} must be tested again before use.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not update this runtime.");}finally{setBusy("");}}
  async function remove(profile:RuntimeProfile){if(!window.confirm(`Delete ${profile.name}? This is available only before the runtime has usage history. Its encrypted key will be removed.`))return;setBusy(`remove:${profile.id}`);try{await request(`/v1/agent-runtimes/${encodeURIComponent(profile.id)}?workspaceId=${encodeURIComponent(workspaceId)}`,{method:"DELETE",headers:{"if-match":String(profile.version)}},"Could not delete this runtime.");setNotice(`${profile.name} deleted.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not delete this runtime.");}finally{setBusy("");}}

  return <section className={styles.module} aria-labelledby="agent-runtime-title">
    <header className={styles.heading}><div><p>WORKSPACE AI RUNTIME</p><h2 id="agent-runtime-title">Choose who writes the first draft</h2><span>Connect an OpenAI-compatible text provider, test it, then assign it to this brand. Board intelligence, memory, and skills are managed only inside each Board.</span></div><button onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?styles.spin:""} size={15}/>Refresh</button></header>
    {error?<div className={styles.error} role="alert"><TriangleAlert size={15}/>{error}</div>:null}{notice?<div className={styles.notice} role="status"><CheckCircle2 size={15}/>{notice}</div>:null}
    <div className={styles.assignment}>
      <span className={assigned?styles.assignedIcon:styles.defaultIcon}>{assigned?<PlugZap size={22}/>:<Bot size={22}/>}</span>
      <div><small>ACTIVE FOR THIS BRAND</small><strong>{assigned?.name??(view.serverHermes.configured?"Server default runtime":"No text provider assigned")}</strong><p>{assigned?`${presetCopy[assigned.preset].label} · ${assigned.textModel}`:view.serverHermes.configured?"Used only because this brand has no workspace runtime assignment.":"Draft assistance will stay unavailable until an owner assigns a tested runtime."}</p></div>
      {isOwner&&assigned?<button onClick={()=>void unassign()} disabled={Boolean(busy)}><CircleOff size={14}/>{busy==="unassign"?"Removing…":"Use server default"}</button>:null}
    </div>
    <div className={styles.toolbar}><div><h3>Runtime connections</h3><p>Keys are encrypted on the server and never returned to this screen.</p></div>{isOwner?<button className={styles.primary} onClick={()=>setFormOpen((value)=>!value)}>{formOpen?"Close form":"Add runtime"}</button>:<span>Owner setup only</span>}</div>
    {formOpen&&isOwner?<form className={styles.form} onSubmit={create}>
      <label>Provider<select value={preset} onChange={(event)=>setPreset(event.target.value as RuntimePreset)}>{Object.entries(presetCopy).map(([value,copy])=><option key={value} value={value}>{copy.label}</option>)}</select><small>{presetCopy[preset].hint}</small></label>
      <label>Connection name<input name="name" required minLength={2} maxLength={100} placeholder="Editorial text provider"/></label>
      {(preset==="ollama"||preset==="custom")?<label className={styles.wide}>Base URL<input name="baseUrl" type="url" required maxLength={500} defaultValue={presetCopy[preset].baseUrl} key={preset} placeholder="https://provider.example/v1"/><small>Private-network endpoints require the deployment owner to enable the explicit server gate.</small></label>:<div className={`${styles.fixed} ${styles.wide}`}><ShieldCheck size={15}/><span><strong>Fixed provider endpoint</strong><small>{presetCopy[preset].baseUrl}</small></span></div>}
      <label>Text model<input name="textModel" required maxLength={160} placeholder={presetCopy[preset].modelPlaceholder}/></label>
      <label>Vision model for image review<input name="visionModel" maxLength={160} placeholder="Exact model ID that accepts image input"/></label>
      <p>News-post creation needs a tested vision model. Testing sends a small generated color sample and uses your provider’s image-input allowance. This checks the connection, not editorial accuracy.</p>
      <label>{preset==="codex-local"?"Local bridge token":"Provider key"} <span>{preset==="ollama"?"Optional":"Required for hosted providers"}</span><input name="apiKey" type="password" autoComplete="new-password" maxLength={1000} required={preset==="openai"||preset==="openrouter"||preset==="codex-local"} placeholder="Saved encrypted; never shown again"/></label>
      <div className={styles.formFoot}><p><KeyRound size={14}/>Saving does not test or assign the provider.</p><button className={styles.primary} disabled={busy==="create"}>{busy==="create"?<Loader2 className={styles.spin} size={14}/>:<PlugZap size={14}/>}Save runtime</button></div>
    </form>:null}
    <div className={styles.cards}>{view.profiles.map((profile)=><article key={profile.id} className={`${styles.card} ${styles[profile.status]}`}>
      <div className={styles.cardHead}><span><Cpu size={18}/></span><div><strong>{profile.name}</strong><small>{presetCopy[profile.preset].label} · {profile.textModel}</small></div><em>{statusCopy(profile.status)}</em></div>
      <dl><div><dt>Image review</dt><dd>{profile.visionModel??"Not configured"}</dd></div><div><dt>Endpoint</dt><dd>{profile.baseUrl}</dd></div><div><dt>Credential</dt><dd>{profile.credentialConfigured?"Encrypted key saved":"No key required/saved"}</dd></div><div><dt>Last check</dt><dd>{stamp(profile.lastCheckedAt)}</dd></div></dl>
      {isOwner?<form key={profile.version} className={styles.visionForm} onSubmit={event=>void saveVision(profile,event)}><label>Vision model<input name="visionModel" defaultValue={profile.visionModel??""} maxLength={160} placeholder="Add an image-capable model ID" disabled={Boolean(busy)||profile.status==="disabled"}/></label><button disabled={Boolean(busy)||profile.status==="disabled"}>Save vision model</button></form>:null}
      {profile.lastError?<p className={styles.profileError}><TriangleAlert size={13}/>{profile.lastError}</p>:null}
      <div className={styles.actions}>{isOwner?<><button onClick={()=>void test(profile)} disabled={Boolean(busy)||profile.status==="disabled"}>{busy===`test:${profile.id}`?<Loader2 className={styles.spin} size={13}/>:<Activity size={13}/>}Test{profile.visionModel?" text + image input":""}</button><button className={styles.assign} onClick={()=>void assign(profile)} disabled={Boolean(busy)||profile.status!=="healthy"||view.assignment?.profileId===profile.id}>{view.assignment?.profileId===profile.id?"Assigned":"Assign to brand"}</button><button onClick={()=>void toggle(profile)} disabled={Boolean(busy)}>{profile.status==="disabled"?"Enable":"Disable"}</button><button className={styles.delete} aria-label={`Delete ${profile.name}`} onClick={()=>void remove(profile)} disabled={Boolean(busy)}><Trash2 size={13}/></button></>:<span>Ask the workspace owner to test or assign this runtime.</span>}</div>
    </article>)}</div>
    {!loading&&view.profiles.length===0?<div className={styles.empty}><Cpu size={24}/><strong>No workspace runtime yet</strong><p>Add OpenAI, OpenRouter, Ollama, LM Studio, vLLM, or another compatible text endpoint. Image and video generation use separate provider modules.</p></div>:null}
    <section className={styles.ledger}><div><h3>Usage ledger</h3><p>Hashes, model, token counts, latency, and outcome only. Prompt and response text are not stored here.</p></div>{view.runs.length?<div className={styles.runList}>{view.runs.slice(0,12).map((run)=><article key={run.id}><span className={run.status===`succeeded`?styles.runOk:styles.runFail}>{run.status===`succeeded`?<CheckCircle2 size={13}/>:<TriangleAlert size={13}/>}</span><div><strong>{run.model}</strong><small>{run.feature.replaceAll("_"," ")} · {run.status}{run.errorCode?` · ${run.errorCode}`:""} · {stamp(run.createdAt)}</small></div><em>{typeof run.inputTokens==="number"||typeof run.outputTokens==="number"?`${(run.inputTokens??0)+(run.outputTokens??0)} tokens`:"Tokens unavailable"}</em><time>{run.latencyMs.toLocaleString()} ms</time></article>)}</div>:<div className={styles.emptyLedger}>No workspace-runtime draft runs yet.</div>}</section>
  </section>;
}
