import { BadRequestException, ForbiddenException, Inject, Injectable, ServiceUnavailableException } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { createCipheriv, randomBytes, randomUUID } from "node:crypto";
import { isIP } from "node:net";
import { lookup } from "node:dns/promises";
import { openAgentRuntimeCredential, AgentProviderError, OpenAICompatibleAgentProvider, type AgentMessage, type AgentImageInput } from "@originpost/agents";
import { agentRunHash, canUseLocalCodex, can, createAgentRuntimeProfile, DomainError, reviseAgentRuntimeProfile, type Actor, type AgentRunLedgerEntry, type AgentRuntimeCredential, type AgentRuntimeProfile, type AuditEvent } from "@originpost/domain";
import { probeImageInput } from "./vision-probe.js";
import { INFRASTRUCTURE } from "../common/tokens.js";
import type { OriginPostInfrastructure } from "../infrastructure/infrastructure.types.js";
import type { AgentRuntimeQueryDto, AssignAgentRuntimeDto, CreateAgentRuntimeDto, UpdateAgentRuntimeDto } from "./dto/agent-runtime.dto.js";

const privateNetworks=[/^10\./,/^127\./,/^169\.254\./,/^192\.168\./,/^172\.(1[6-9]|2\d|3[01])\./,/^0\./,/^::1$/i,/^fc/i,/^fd/i,/^fe80:/i];
const isPrivate=(value:string)=>privateNetworks.some((pattern)=>pattern.test(value));
const safeError=(error:unknown)=>error instanceof AgentProviderError?{code:error.code,message:error.message}:{code:"provider_failed",message:"The AI runtime could not complete this request."};

@Injectable()
export class AgentRuntimeService{
  constructor(@Inject(INFRASTRUCTURE)private readonly infrastructure:OriginPostInfrastructure,private readonly config:ConfigService){}
  private readable(actor:Actor){if(!can(actor.role,"content:read"))throw new ForbiddenException("You cannot view AI runtimes.");}
  private owner(actor:Actor){if((actor.actorType&&actor.actorType!=="human")||!can(actor.role,"workspace:manage"))throw new ForbiddenException("Only a workspace owner can change AI runtimes.");}
  private audit(workspaceId:string,actor:Actor,action:string,detail:Record<string,unknown>,contentItemId?:string):AuditEvent{return{id:`evt_${randomUUID()}`,workspaceId,...(contentItemId?{contentItemId}:{}),actorId:actor.id,actorType:actor.actorType??"human",action,detail,createdAt:new Date().toISOString()};}
  private key(){const raw=this.config.get<string>("CREDENTIAL_ENCRYPTION_KEY")?.trim();if(!raw)return null;const key=/^[a-f0-9]{64}$/i.test(raw)?Buffer.from(raw,"hex"):Buffer.from(raw,"base64");return key.length===32?key:null;}
  private seal(workspaceId:string,profileId:string,value:string):AgentRuntimeCredential{const key=this.key();if(!key)throw new DomainError("Set a 32-byte CREDENTIAL_ENCRYPTION_KEY before saving an AI provider key.","agent_runtime_encryption_required",409);const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",key,iv);cipher.setAAD(Buffer.from(`${workspaceId}:${profileId}:agent-runtime:v1`));const ciphertext=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return{keyVersion:"v1",algorithm:"aes-256-gcm",iv:iv.toString("base64"),authTag:cipher.getAuthTag().toString("base64"),ciphertext:ciphertext.toString("base64")};}
  private open(workspaceId:string,profileId:string,value:AgentRuntimeCredential|null){if(!value)return undefined;const key=this.key();if(!key)throw new DomainError("AI provider credential encryption is not configured.","agent_runtime_encryption_required",409);try{return openAgentRuntimeCredential(workspaceId,profileId,value,key);}catch{throw new DomainError("The AI provider key cannot be opened. Save it again.","agent_runtime_credential_invalid",409);}}
  private localCodexEndpoint() {
    const raw = this.config.get<string>("LOCAL_CODEX_BASE_URL");
    if (!raw) throw new DomainError("Start the local Codex bridge and configure LOCAL_CODEX_BASE_URL on this API server.", "local_codex_setup", 409);
    let url: URL; try { url = new URL(raw); } catch { throw new DomainError("Invalid local Codex bridge URL.", "local_codex_setup", 409); }
    if (url.protocol !== "http:" || !["127.0.0.1", "host.docker.internal"].includes(url.hostname) || url.pathname.replace(/\/$/, "") !== "/v1" || url.username || url.password || url.search || url.hash) throw new DomainError("The Codex bridge must use its server-owned local HTTP endpoint.", "local_codex_setup", 409);
    return url.toString().replace(/\/$/, "");
  }
  private async assertSafe(profile:AgentRuntimeProfile,actor?:Actor){if(profile.preset==="codex-local"){
    if(!canUseLocalCodex({authMode:this.config.get<string>("AUTH_MODE")??"single-user",workspaceId:profile.workspaceId,ownerWorkspaceId:this.config.get<string>("LOCAL_CODEX_OWNER_WORKSPACE_ID"),ownerUserId:this.config.get<string>("LOCAL_CODEX_OWNER_USER_ID"),actor}) || (this.config.get<string>("AUTH_MODE")==="sessions" && profile.createdBy!==actor?.id)) throw new DomainError("The personal Codex runtime requires single-owner access or its explicitly configured session owner and workspace.","local_codex_scope",403);
    this.localCodexEndpoint();return;}const url=new URL(profile.baseUrl);const fixed=profile.preset==="openai"||profile.preset==="openrouter";if(fixed)return;const allowPrivate=this.config.get<boolean>("AGENT_ALLOW_PRIVATE_ENDPOINTS")===true;const production=this.config.get<string>("NODE_ENV")==="production";if(production&&url.protocol!=="https:"&&!allowPrivate)throw new DomainError("Production AI endpoints must use HTTPS unless private endpoints are explicitly allowed.","agent_runtime_endpoint_blocked",409);if(allowPrivate)return;if(["localhost","localhost.localdomain"].includes(url.hostname.toLowerCase())||(isIP(url.hostname)&&isPrivate(url.hostname)))throw new DomainError("Private AI endpoints are disabled. The server owner can enable them for Ollama or a trusted local gateway.","agent_runtime_endpoint_blocked",409);try{const addresses=await lookup(url.hostname,{all:true,verbatim:true});if(!addresses.length||addresses.some((entry)=>isPrivate(entry.address)))throw new DomainError("The AI endpoint resolves to a private address that is not allowed.","agent_runtime_endpoint_blocked",409);}catch(error){if(error instanceof DomainError)throw error;throw new DomainError("The AI endpoint hostname could not be verified.","agent_runtime_endpoint_unverified",409);}}
  private async provider(workspaceId:string,profileId:string,model?:string,expectedVersion?:number,actor?:Actor){const context=await this.infrastructure.agentRuntimeRepository.getProfileExecutionContext(workspaceId,profileId);if(!context)throw new DomainError("AI runtime not found.","agent_runtime_not_found",404);if(expectedVersion!==undefined&&context.profile.version!==expectedVersion)throw new DomainError("The runtime changed before execution. Test the updated configuration first.","version_conflict",409);await this.assertSafe(context.profile,actor);const apiKey=this.open(workspaceId,profileId,context.credential);return{profile:context.profile,provider:new OpenAICompatibleAgentProvider({baseUrl:context.profile.preset==="codex-local"?this.localCodexEndpoint():context.profile.baseUrl,textModel:model??context.profile.textModel,...(apiKey?{apiKey}:{})})};}
  async list(workspaceId:string,query:AgentRuntimeQueryDto,actor:Actor){this.readable(actor);const profiles=await this.infrastructure.agentRuntimeRepository.listProfiles(workspaceId);const assignment=query.brandId?await this.infrastructure.agentRuntimeRepository.getAssignment(workspaceId,query.brandId):null;const runs=await this.infrastructure.agentRuntimeRepository.listRuns(workspaceId,undefined,query.limit);return{profiles,assignment,runs,serverHermes:{configured:Boolean(this.infrastructure.hermes),fallbackOnlyWhenUnassigned:true}};}
  async create(workspaceId:string,dto:CreateAgentRuntimeDto,actor:Actor){this.owner(actor);const id=`agent_runtime_${randomUUID()}`;const apiKey=dto.apiKey?.trim();const result=createAgentRuntimeProfile({id,workspaceId,name:dto.name,preset:dto.preset,...(dto.baseUrl?{baseUrl:dto.baseUrl}:{}),textModel:dto.textModel,...(dto.visionModel?{visionModel:dto.visionModel}:{}),credentialConfigured:Boolean(apiKey),actor});await this.assertSafe(result.profile,actor);if(dto.assignBrandId)throw new BadRequestException("Test the runtime first, then assign it to a brand.");await this.infrastructure.agentRuntimeRepository.createProfile(result.profile,apiKey?this.seal(workspaceId,id,apiKey):null,result.event);return result.profile;}
  async update(workspaceId:string,id:string,expectedVersion:number|undefined,dto:UpdateAgentRuntimeDto,actor:Actor){this.owner(actor);if(!expectedVersion)throw new DomainError("Use If-Match with the current runtime version.","version_required",428);const current=await this.infrastructure.agentRuntimeRepository.getProfile(workspaceId,id);if(!current)throw new DomainError("AI runtime not found.","agent_runtime_not_found",404);const apiKey=dto.apiKey?.trim();const result=reviseAgentRuntimeProfile(current,{...(dto.name!==undefined?{name:dto.name}:{}),...(dto.baseUrl!==undefined?{baseUrl:dto.baseUrl}:{}),...(dto.textModel!==undefined?{textModel:dto.textModel}:{}),...(dto.visionModel!==undefined?{visionModel:dto.visionModel}:{}),...(apiKey?{credentialConfigured:true}:{}),...(dto.disabled!==undefined?{disabled:dto.disabled}:{}),actor});await this.assertSafe(result.profile,actor);const saved=await this.infrastructure.agentRuntimeRepository.updateProfile(result.profile,expectedVersion,apiKey?this.seal(workspaceId,id,apiKey):undefined,result.event);if(!saved)throw new DomainError("This AI runtime changed. Refresh and try again.","version_conflict",409);return saved;}
  async test(workspaceId:string,id:string,actor:Actor){this.owner(actor);const {profile,provider}=await this.provider(workspaceId,id,undefined,undefined,actor);const checkedAt=new Date().toISOString();try{const result=await provider.inspect();if(profile.visionModel){const vision=await this.provider(workspaceId,id,profile.visionModel,profile.version,actor);await vision.provider.inspect();await probeImageInput(vision.provider);}const event=this.audit(workspaceId,actor,"agent-runtime.tested",{profileId:id,status:"healthy",model:result.model,availableModelCount:result.availableModels.length,visionModel:profile.visionModel??null,imageInputTested:Boolean(profile.visionModel)});const saved=await this.infrastructure.agentRuntimeRepository.updateHealth(workspaceId,id,profile.version,{status:"healthy",checkedAt},event);if(!saved)throw new DomainError("This AI runtime changed during the test. Refresh and try again.","version_conflict",409);return{ok:true,profile:saved,model:result.model,availableModelCount:result.availableModels.length};}catch(error){if(error instanceof DomainError)throw error;const safe=safeError(error);const event=this.audit(workspaceId,actor,"agent-runtime.tested",{profileId:id,status:"error",errorCode:safe.code});const saved=await this.infrastructure.agentRuntimeRepository.updateHealth(workspaceId,id,profile.version,{status:"error",checkedAt,error:safe.message},event);return{ok:false,profile:saved??profile,error:safe};}}
  async assign(workspaceId:string,id:string,dto:AssignAgentRuntimeDto,actor:Actor){this.owner(actor);const brand=await this.infrastructure.organizationRepository.getBrand(workspaceId,dto.brandId);if(!brand||brand.status!=="active")throw new DomainError("Active brand not found.","brand_not_found",404);const profile=await this.infrastructure.agentRuntimeRepository.getProfile(workspaceId,id);if(!profile)throw new DomainError("AI runtime not found.","agent_runtime_not_found",404);await this.assertSafe(profile,actor);const assignedAt=new Date().toISOString();const assignment={workspaceId,brandId:dto.brandId,profileId:id,assignedBy:actor.id,assignedAt};await this.infrastructure.agentRuntimeRepository.assign(assignment,this.audit(workspaceId,actor,"agent-runtime.assigned",{profileId:id,brandId:dto.brandId,status:profile.status}));return assignment;}
  async unassign(workspaceId:string,brandId:string,actor:Actor){this.owner(actor);const removed=await this.infrastructure.agentRuntimeRepository.unassign(workspaceId,brandId,this.audit(workspaceId,actor,"agent-runtime.unassigned",{brandId}));return{unassigned:removed,brandId};}
  async remove(workspaceId:string,id:string,expectedVersion:number|undefined,actor:Actor){this.owner(actor);if(!expectedVersion)throw new DomainError("Use If-Match with the current runtime version.","version_required",428);if((await this.infrastructure.agentRuntimeRepository.listRuns(workspaceId,id,1)).length)throw new DomainError("This runtime has usage history and cannot be deleted. Disable it to preserve the audit ledger.","agent_runtime_history_retained",409);if(!await this.infrastructure.agentRuntimeRepository.removeProfile(workspaceId,id,expectedVersion,this.audit(workspaceId,actor,"agent-runtime.removed",{profileId:id,expectedVersion})))throw new DomainError("This AI runtime changed or was not found.","version_conflict",409);return{removed:true,id};}
  async runs(workspaceId:string,id:string,limit:number,actor:Actor){this.readable(actor);return this.infrastructure.agentRuntimeRepository.listRuns(workspaceId,id,limit);}
  async runDraft(input:{workspaceId:string;brandId:string;contentItemId:string;actor:Actor;messages:AgentMessage[]}){
    return this.runText(input, "draft_assist");
  }
  async runCopyReview(input:{workspaceId:string;brandId:string;contentItemId:string;actor:Actor;messages:AgentMessage[]}){
    return this.runText(input, "copy_review");
  }
  async imageReviewCapability(workspaceId:string,brandId:string){
    const context=await this.infrastructure.agentRuntimeRepository.getExecutionContext(workspaceId,brandId);
    return Boolean(context?.profile.visionModel);
  }
  async runImageReview(input:{workspaceId:string;brandId:string;contentItemId:string;actor:Actor;messages:AgentMessage[];imageInputs:AgentImageInput[]}){
    return this.runText(input,"image_review");
  }
  private async runText(input:{workspaceId:string;brandId:string;contentItemId:string;actor:Actor;messages:AgentMessage[];imageInputs?:AgentImageInput[]},feature:AgentRunLedgerEntry["feature"]){
    // A reviewer gets a fresh session; never inherit the writer's conversation.
    const sessionKey=feature !== "draft_assist" ? `originpost:${input.workspaceId}:${input.contentItemId}:review:${randomUUID()}` : `originpost:${input.workspaceId}:${input.contentItemId}`;
    const assignment=await this.infrastructure.agentRuntimeRepository.getAssignment(input.workspaceId,input.brandId);if(!assignment){if(feature==="image_review")throw new ServiceUnavailableException("Assign a tested vision model before checking an image.");if(!this.infrastructure.hermes)throw new ServiceUnavailableException("Assign a tested AI runtime to this brand before asking for a draft.");return this.infrastructure.hermes.run({sessionKey,messages:input.messages,temperature:0.2,maxTokens:1800});}
    const context=await this.infrastructure.agentRuntimeRepository.getExecutionContext(input.workspaceId,input.brandId);if(!context)throw new ServiceUnavailableException("The assigned AI runtime is not healthy. Test or replace it before asking for a draft.");const model=feature==="image_review"?context.profile.visionModel:context.profile.textModel;if(!model)throw new ServiceUnavailableException("Configure and test a vision model for this brand.");const {provider}=await this.provider(input.workspaceId,context.profile.id,model,context.profile.version,input.actor);const started=Date.now();const requestSha256=agentRunHash(input.imageInputs?{messages:input.messages,imageInputs:input.imageInputs}:input.messages);const at=new Date().toISOString();
    try{const result=await provider.run({sessionKey,messages:input.messages,...(input.imageInputs?{imageInputs:input.imageInputs}:{}),temperature:0.2,maxTokens:feature==="image_review"?4000:1800});const run:AgentRunLedgerEntry={id:`agent_run_${randomUUID()}`,workspaceId:input.workspaceId,brandId:input.brandId,profileId:context.profile.id,contentItemId:input.contentItemId,feature,model:result.model,status:"succeeded",requestSha256,responseSha256:agentRunHash(result.text),...(typeof result.usage?.inputTokens==="number"?{inputTokens:result.usage.inputTokens}:{}),...(typeof result.usage?.outputTokens==="number"?{outputTokens:result.usage.outputTokens}:{}),latencyMs:Math.max(0,Date.now()-started),createdBy:input.actor.id,createdAt:at};await this.infrastructure.agentRuntimeRepository.recordRun(run,this.audit(input.workspaceId,input.actor,"agent-runtime.run-succeeded",{runId:run.id,profileId:run.profileId,brandId:run.brandId,feature:run.feature,model:run.model,inputTokens:run.inputTokens,outputTokens:run.outputTokens,latencyMs:run.latencyMs},input.contentItemId));return result;}catch(error){const safe=safeError(error);const run:AgentRunLedgerEntry={id:`agent_run_${randomUUID()}`,workspaceId:input.workspaceId,brandId:input.brandId,profileId:context.profile.id,contentItemId:input.contentItemId,feature,model,status:"failed",requestSha256,latencyMs:Math.max(0,Date.now()-started),errorCode:safe.code,createdBy:input.actor.id,createdAt:at};await this.infrastructure.agentRuntimeRepository.recordRun(run,this.audit(input.workspaceId,input.actor,"agent-runtime.run-failed",{runId:run.id,profileId:run.profileId,brandId:run.brandId,feature:run.feature,model:run.model,errorCode:safe.code,latencyMs:run.latencyMs},input.contentItemId));throw new ServiceUnavailableException(`${safe.message} OriginPost did not switch to another provider.`);}
  }
}
