import { randomUUID } from "node:crypto";
import { ConflictException, ForbiddenException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { approveFirstCommentIntent, bindFirstCommentToProof, canonicalSha256, createFirstCommentIntent, reviseFirstCommentIntent, submitFirstCommentIntent, transitionFirstComment, type Actor, type AuditEvent, type FirstCommentIntent } from "@originpost/domain";
import { INFRASTRUCTURE } from "../common/tokens.js";
import type { OriginPostInfrastructure } from "../infrastructure/infrastructure.types.js";
import type { ApproveFirstCommentDto, AttestFirstCommentDto, CreateFirstCommentDto, FirstCommentVersionDto, ReconcileFirstCommentDto, ReviseFirstCommentDto } from "./first-comment.dto.js";

@Injectable()
export class FirstCommentService {
  constructor(@Inject(INFRASTRUCTURE) private readonly infrastructure:OriginPostInfrastructure,private readonly config:ConfigService){}
  async capability(workspaceId:string,contentItemId:string,targetId:string,_actor:Actor){const {item,target}=await this.lineage(workspaceId,contentItemId,targetId);const capability=await this.infrastructure.connectors.getFirstComment(target.platform as "instagram"|"facebook").firstCommentCapability({workspaceId,accountId:target.accountId,platform:target.platform as "instagram"|"facebook"});return{data:{targetId,itemVersion:item.version,capability}};}
  async list(workspaceId:string,contentItemId:string,_actor:Actor){await this.item(workspaceId,contentItemId);return{data:await this.infrastructure.firstCommentRepository.list(workspaceId,contentItemId)};}
  async get(workspaceId:string,contentItemId:string,intentId:string,_actor:Actor){return{data:await this.record(workspaceId,contentItemId,intentId)};}
  async create(workspaceId:string,contentItemId:string,dto:CreateFirstCommentDto,actor:Actor){this.requireHuman(actor);const {item,target}=await this.lineage(workspaceId,contentItemId,dto.targetId);const capability=await this.infrastructure.connectors.getFirstComment(target.platform as "instagram"|"facebook").firstCommentCapability({workspaceId,accountId:target.accountId,platform:target.platform as "instagram"|"facebook"});if(capability.state!=="supported")throw new ConflictException(capability.reason);const intent=createFirstCommentIntent({item,targetId:dto.targetId,body:dto.body,actor});const created=await this.infrastructure.firstCommentRepository.create(intent,this.audit(intent,actor,"first_comment.created"));if(!created)throw new ConflictException("This target already has an active first comment.");return{data:{intent,proofs:[]},meta:{approvalRequired:true}};}
  async revise(workspaceId:string,contentItemId:string,intentId:string,dto:ReviseFirstCommentDto,actor:Actor){const record=await this.record(workspaceId,contentItemId,intentId);this.expected(record.intent,dto.expectedVersion);const next=reviseFirstCommentIntent(record.intent,{body:dto.body,actor});await this.save(next,record.intent.version,["draft"],actor,"first_comment.revised");return{data:{...record,intent:next}};}
  async submit(workspaceId:string,contentItemId:string,intentId:string,dto:FirstCommentVersionDto,actor:Actor){const record=await this.record(workspaceId,contentItemId,intentId);this.expected(record.intent,dto.expectedVersion);const next=submitFirstCommentIntent(record.intent,actor);await this.save(next,record.intent.version,["draft"],actor,"first_comment.submitted");return{data:{...record,intent:next}};}
  async approve(workspaceId:string,contentItemId:string,intentId:string,dto:ApproveFirstCommentDto,actor:Actor){this.requireApprover(actor);const record=await this.record(workspaceId,contentItemId,intentId);this.expected(record.intent,dto.expectedVersion);const {item,target}=await this.lineage(workspaceId,contentItemId,record.intent.targetId);if(target.draftId!==record.intent.draftId||target.accountId!==record.intent.accountId||target.platform!==record.intent.platform)throw new ConflictException("The publish target changed after this first comment was drafted.");const draft=item.drafts.find((entry)=>entry.id===target.draftId);if(!draft||draft.contentSha256!==record.intent.draftSha256)throw new ConflictException("The approved target draft changed.");const capability=await this.infrastructure.connectors.getFirstComment(record.intent.platform).firstCommentCapability({workspaceId,accountId:record.intent.accountId,platform:record.intent.platform});if(capability.state!=="supported")throw new ConflictException(capability.reason);const authority=await this.approvalAuthority(workspaceId,actor);let mode:"two_person"|"single_owner_override"="two_person";const now=new Date().toISOString();if(actor.id===record.intent.requestedBy){if(actor.role!=="owner"||!authority.soleOwner||!dto.singleOwnerOverride||!dto.secondConfirmation)throw new ForbiddenException("Self-approval is allowed only for the sole owner with the explicit second confirmation.");mode="single_owner_override";}let next=approveFirstCommentIntent(record.intent,{actorId:actor.id,actorType:"human",approvedAt:now,mode,...(mode==="single_owner_override"?{secondConfirmedAt:now}:{})});const proof=item.proofs.find((entry)=>entry.contentItemId===item.id&&entry.draftId===next.draftId&&entry.draftSha256===next.draftSha256&&entry.platform===next.platform&&entry.accountId===next.accountId);if(proof)next=bindFirstCommentToProof(next,proof,now);await this.save(next,record.intent.version,["pending_approval"],actor,"first_comment.approved");await this.enqueue(next);return{data:{...record,intent:next},meta:{accepted:true,waitingForPublication:next.status==="approved"}};}
  async cancel(workspaceId:string,contentItemId:string,intentId:string,dto:FirstCommentVersionDto,actor:Actor){const record=await this.record(workspaceId,contentItemId,intentId);this.expected(record.intent,dto.expectedVersion);if(record.intent.status==="processing"||record.intent.status==="succeeded"||record.intent.status==="uncertain")throw new ConflictException("This first comment cannot be cancelled after a provider write may have started.");if(actor.id!==record.intent.requestedBy&&actor.role!=="manager"&&actor.role!=="owner")throw new ForbiddenException("Only the author, manager, or owner can cancel this first comment.");const next=transitionFirstComment(record.intent,"cancelled",new Date().toISOString());await this.save(next,record.intent.version,[record.intent.status],actor,"first_comment.cancelled");return{data:{...record,intent:next}};}
  async reconcile(workspaceId:string,contentItemId:string,intentId:string,dto:ReconcileFirstCommentDto,actor:Actor){this.requireApprover(actor);const record=await this.record(workspaceId,contentItemId,intentId);this.expected(record.intent,dto.expectedVersion);if(record.intent.status!=="uncertain")throw new ConflictException("Only an uncertain first comment can be reconciled.");const now=new Date().toISOString();const transitioned=transitionFirstComment(record.intent,"queued",now,dto.outcome==="confirmed_not_sent"?"A human confirmed that the provider did not create the first comment.":"A human requested a read-only provider inspection.");const next:FirstCommentIntent=dto.outcome==="confirmed_not_sent"?{...transitioned,executionMode:"write",providerCommentId:undefined,providerAcceptedAt:undefined,providerResponseSha256:undefined}:{...transitioned,executionMode:"reconcile"};await this.save(next,record.intent.version,["uncertain"],actor,dto.outcome==="confirmed_not_sent"?"first_comment.confirmed_not_sent":"first_comment.reconciliation_requested");await this.enqueue(next);return{data:{...record,intent:next},meta:{accepted:true,providerWriteMayRetry:dto.outcome==="confirmed_not_sent",readOnlyInspection:dto.outcome==="inspect_provider"}};}
  async attest(workspaceId:string,contentItemId:string,intentId:string,dto:AttestFirstCommentDto,actor:Actor){this.requireApprover(actor);const record=await this.record(workspaceId,contentItemId,intentId);this.expected(record.intent,dto.expectedVersion);if(record.intent.status!=="uncertain"||!record.intent.publishProofId||!record.intent.externalPostId)throw new ConflictException("Only an uncertain, proof-bound first comment can accept operator evidence.");const now=new Date().toISOString();if(Date.parse(dto.occurredAt)>Date.now()+60_000)throw new ConflictException("Attestation time cannot be in the future.");const noteSha256=canonicalSha256({schemaVersion:"originpost.first-comment-note.v1",note:dto.note.normalize("NFC").trim()});const observationSha256=canonicalSha256({schemaVersion:"originpost.first-comment-operator-evidence.v1",actorId:actor.id,occurredAt:dto.occurredAt,evidenceUrl:dto.evidenceUrl,noteSha256,intentId:record.intent.id,externalPostId:record.intent.externalPostId});const result=await this.infrastructure.firstCommentRepository.resolveWithProof({workspaceId,intentId,proofId:`first_comment_proof_${randomUUID()}`,resolvedAt:now,evidence:{grade:"operator_attested",actorId:actor.id,occurredAt:dto.occurredAt,evidenceUrl:dto.evidenceUrl,noteSha256,observationSha256,observedAt:now}},this.audit(record.intent,actor,"first_comment.operator_attested"));if(!result)throw new ConflictException("The first comment changed before evidence was saved.");return{data:result};}
  private async item(workspaceId:string,id:string){const item=await this.infrastructure.repository.get(workspaceId,id);if(!item)throw new NotFoundException("Content item not found.");return item;}
  private async lineage(workspaceId:string,contentItemId:string,targetId:string){const item=await this.item(workspaceId,contentItemId);const target=item.targets.find((entry)=>entry.id===targetId);if(!target)throw new NotFoundException("Publish target not found.");if(target.platform!=="instagram"&&target.platform!=="facebook")throw new ConflictException("First comments are supported only for Instagram and Facebook Page targets.");const account=await this.infrastructure.connectedAccountRepository.get(workspaceId,target.accountId);if(!account||account.brandId!==item.brandId||account.platform!==target.platform)throw new ConflictException("Publish target no longer matches its workspace, brand, platform, and account.");if(account.status!=="healthy"&&account.status!=="expiring")throw new ConflictException("The connected account needs attention before a first comment can be approved.");return{item,target,account};}
  private async record(workspaceId:string,contentItemId:string,intentId:string){const value=await this.infrastructure.firstCommentRepository.get(workspaceId,intentId);if(!value||value.intent.contentItemId!==contentItemId)throw new NotFoundException("First comment not found.");return value;}
  private expected(intent:FirstCommentIntent,value:number){if(value!==intent.version)throw new ConflictException("This first comment changed. Refresh it and try again.");}
  private async save(next:FirstCommentIntent,expectedVersion:number,statuses:FirstCommentIntent["status"][],actor:Actor,action:string){const saved=await this.infrastructure.firstCommentRepository.compareAndSet(next,expectedVersion,statuses,this.audit(next,actor,action));if(!saved)throw new ConflictException("This first comment changed. Refresh it and try again.");}
  private audit(intent:FirstCommentIntent,actor:Actor,action:string):AuditEvent{return{id:`audit_${randomUUID()}`,workspaceId:intent.workspaceId,contentItemId:intent.contentItemId,actorId:actor.id,actorType:actor.actorType??"human",action,detail:{intentId:intent.id,targetId:intent.targetId,bodySha256:intent.bodySha256,immutableIntentSha256:intent.immutableIntentSha256},createdAt:new Date().toISOString()};}
  private requireHuman(actor:Actor){if(actor.actorType&&actor.actorType!=="human")throw new ForbiddenException("First-comment changes require an authenticated human.");if(actor.role==="viewer")throw new ForbiddenException("Viewers cannot change first comments.");}
  private requireApprover(actor:Actor){this.requireHuman(actor);if(actor.role!=="manager"&&actor.role!=="owner")throw new ForbiddenException("Only a manager or owner can approve or reconcile first comments.");}
  private async approvalAuthority(workspaceId:string,actor:Actor){if(this.config.get<string>("AUTH_MODE")!=="sessions"){const localOwnerId=this.config.get<string>("BOOTSTRAP_USER_ID")??"local-owner";if(actor.id!==localOwnerId||actor.role!=="owner")throw new ForbiddenException("Only the trusted local owner can approve in single-user mode.");return{soleOwner:true};}const members=(await this.infrastructure.authRepository.listWorkspaceMembers(workspaceId)).filter((member)=>member.status==="active"&&(member.role==="owner"||member.role==="manager"));const current=members.find((member)=>member.userId===actor.id);if(!current||current.role!==actor.role)throw new ForbiddenException("An active owner or manager membership is required.");return{soleOwner:members.length===1&&current.role==="owner"};}
  private async enqueue(intent:FirstCommentIntent){if(!this.infrastructure.firstCommentQueue)return;await this.infrastructure.firstCommentQueue.add("execute",{workspaceId:intent.workspaceId,contentItemId:intent.contentItemId,intentId:intent.id},{jobId:`first-comment-${intent.id}-v${intent.version}`,attempts:1,removeOnComplete:100,removeOnFail:500});}
}
