import "reflect-metadata";
import { ConfigService } from "@nestjs/config";
import { FastifyAdapter, type NestFastifyApplication } from "@nestjs/platform-fastify";
import { Test } from "@nestjs/testing";
import request from "supertest";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { AppModule } from "../src/app.module.js";
import { configureApp } from "../src/configure-app.js";
import { INFRASTRUCTURE } from "../src/common/tokens.js";
import type { OriginPostInfrastructure } from "../src/infrastructure/infrastructure.types.js";
import { startE2eApp, withCurrentScheduleConflictAcknowledgement } from "./test-app.js";
import { collaboratorInviteProof, markTargetStatus, startPublishAttempt, type Actor, type MediaAsset, type ProviderPublishOperation } from "@originpost/domain";

describe("Instagram collaborator approval API",()=>{
  let app:NestFastifyApplication;let infrastructure:OriginPostInfrastructure;
  beforeAll(async()=>{Object.assign(process.env,{NODE_ENV:"test",AUTH_MODE:"single-user",DATABASE_URL:"",REDIS_URL:"",BOOTSTRAP_USER_ID:"local-owner",BOOTSTRAP_USER_NAME:"Local Owner",REVIEW_LINK_SECRET:"test-review-link-secret-with-more-than-32-characters",MEDIA_DELIVERY_SECRET:"test-media-delivery-secret-with-more-than-32-characters",AUTOMATION_DELIVERY_ENABLED:"false"});const fixture=await Test.createTestingModule({imports:[AppModule]}).compile();app=fixture.createNestApplication<NestFastifyApplication>(new FastifyAdapter({logger:false}),{logger:["error"]});configureApp(app,app.get(ConfigService));await startE2eApp(app);infrastructure=app.get(INFRASTRUCTURE);const now=new Date().toISOString();await infrastructure.connectedAccountRepository.save({id:"instagram-collab-account",workspaceId:"default",brandId:"brand_default",platform:"instagram",displayName:"@publisher",externalAccountId:"provider-publisher",capabilities:["profile_read","media_publish","collaborator_publish","collaborator_status_read"],status:"healthy",createdBy:"local-owner",createdAt:now,updatedAt:now},{id:"audit-instagram-collab-account",workspaceId:"default",actorId:"local-owner",actorType:"human",action:"test.account-created",detail:{},createdAt:now});});
  afterAll(async()=>{if(app)await app.close();});
  async function prepared(){const created=await request(app.getHttpServer()).post("/v1/content-items").send({workspaceId:"default",title:"Collaborator approval route test"}).expect(201);const upload=await request(app.getHttpServer()).post("/v1/media-assets/uploads").send({workspaceId:"default",kind:"image",purpose:"creative",fileName:"fixture.png",contentType:"image/png",sizeBytes:1,sha256:"a".repeat(64),rights:"owned",altText:"Fixture"}).expect(201);await request(app.getHttpServer()).post(`/v1/media-assets/${upload.body.asset.id}/complete`).send({workspaceId:"default"}).expect(200);await request(app.getHttpServer()).post(`/v1/content-items/${created.body.id}/sources`).send({kind:"url",title:"Official source",url:"https://example.com/source",rights:"reference-only",confidence:100}).expect(201);const drafted=await request(app.getHttpServer()).post(`/v1/content-items/${created.body.id}/drafts`).send({platform:"instagram",format:"image",title:"Checked title",caption:"Checked caption",mediaIds:[upload.body.asset.id]}).expect(201);const draftId=drafted.body.drafts.at(-1).id as string;await request(app.getHttpServer()).post(`/v1/content-items/${created.body.id}/approvals`).send({decision:"approved",draftId}).expect(201);return{id:created.body.id as string,draftId};}
  async function preparedReel(){const suffix=crypto.randomUUID();const created=await request(app.getHttpServer()).post("/v1/content-items").send({workspaceId:"default",title:"Reel cover approval route test"}).expect(201);const now=new Date().toISOString();const base=(id:string,kind:"image"|"video",sha256:string):MediaAsset=>({id,workspaceId:"default",brandId:"brand_default",version:1,kind,purpose:"creative",fileName:`${id}.${kind==="image"?"png":"mp4"}`,contentType:kind==="image"?"image/png":"video/mp4",sizeBytes:100,sha256,objectKey:`qa/${id}`,status:"ready",inspectionStatus:"ready",widthPixels:1080,heightPixels:1920,...(kind==="video"?{durationMs:60000}:{}),rights:"owned",createdBy:"local-owner",createdAt:now,uploadExpiresAt:new Date(Date.now()+3600000).toISOString(),readyAt:now});const video=base(`video-${suffix}`,"video","b".repeat(64));const cover=base(`cover-${suffix}`,"image","c".repeat(64));for(const asset of [video,cover])await infrastructure.mediaRepository.save(asset,{id:`audit-${asset.id}`,workspaceId:"default",actorId:"local-owner",actorType:"human",action:"test.media-ready",detail:{assetId:asset.id},createdAt:now});await request(app.getHttpServer()).post(`/v1/content-items/${created.body.id}/sources`).send({kind:"url",title:"Official source",url:"https://example.com/reel-source",rights:"reference-only",confidence:100}).expect(201);const drafted=await request(app.getHttpServer()).post(`/v1/content-items/${created.body.id}/drafts`).send({platform:"instagram",format:"reel",title:"Checked Reel",caption:"Checked Reel caption",mediaIds:[video.id]}).expect(201);const draftId=drafted.body.drafts.at(-1).id as string;await request(app.getHttpServer()).post(`/v1/content-items/${created.body.id}/approvals`).send({decision:"approved",draftId}).expect(201);return{id:created.body.id as string,draftId,video,cover};}
  it("normalizes on the server, records explicit approval, and schedules only by approval id",async()=>{const item=await prepared();const capability=await request(app.getHttpServer()).get(`/v1/content-items/${item.id}/instagram-collaborators/capability?accountId=instagram-collab-account&draftId=${item.draftId}`).expect(200);expect(capability.body).toMatchObject({accountId:"instagram-collab-account",publishingUsername:"publisher",capability:{state:"supported",maxCollaborators:3}});
    const candidate=await request(app.getHttpServer()).post(`/v1/content-items/${item.id}/instagram-collaborators/candidates`).send({draftId:item.draftId,accountId:"instagram-collab-account",collaborators:[" @Guest.One ","guest_two","guest_two"]}).expect(201);expect(candidate.body).toMatchObject({status:"pending_approval",settings:{collaborators:["guest.one","guest_two"],approvedSettingsSha256:expect.stringMatching(/^[a-f0-9]{64}$/)}});
    const approved=await request(app.getHttpServer()).post(`/v1/content-items/${item.id}/instagram-collaborators/candidates/${candidate.body.id}/approve`).send({note:"Human checked both accounts"}).expect(201);expect(approved.body).toMatchObject({status:"approved",approvedBy:"local-owner",approvalId:expect.stringContaining("approval_")});
    const scheduleBody={platform:"instagram",accountId:"instagram-collab-account",draftId:item.draftId,scheduledFor:"2099-01-01T12:00:00.000Z",deliveryMode:"auto_publish",instagramCollaboratorApprovalId:approved.body.approvalId};const scheduled=await request(app.getHttpServer()).post(`/v1/content-items/${item.id}/schedule`).send(await withCurrentScheduleConflictAcknowledgement(app,item.id,scheduleBody));expect(scheduled.status,JSON.stringify(scheduled.body)).toBe(201);expect(scheduled.body.targets.at(-1).settings).toMatchObject({collaborators:["guest.one","guest_two"],approvalBinding:{accountId:"instagram-collab-account",approvedSettingsSha256:approved.body.settings.approvedSettingsSha256}});
  });
  it("rejects client-supplied hashes and cross-content approval reuse",async()=>{const first=await prepared();const second=await prepared();await request(app.getHttpServer()).post(`/v1/content-items/${first.id}/instagram-collaborators/candidates`).send({draftId:first.draftId,accountId:"instagram-collab-account",collaborators:["guest"],approvedSettingsSha256:"0".repeat(64)}).expect(400);const candidate=await request(app.getHttpServer()).post(`/v1/content-items/${first.id}/instagram-collaborators/candidates`).send({draftId:first.draftId,accountId:"instagram-collab-account",collaborators:["guest"]}).expect(201);const approved=await request(app.getHttpServer()).post(`/v1/content-items/${first.id}/instagram-collaborators/candidates/${candidate.body.id}/approve`).send({}).expect(201);await request(app.getHttpServer()).post(`/v1/content-items/${second.id}/schedule`).send({platform:"instagram",accountId:"instagram-collab-account",draftId:second.draftId,scheduledFor:"2099-01-01T12:00:00.000Z",deliveryMode:"auto_publish",instagramCollaboratorApprovalId:approved.body.approvalId}).expect(409);});
  it("does not expose status for another content lineage",async()=>{const first=await prepared();const second=await prepared();const status=await request(app.getHttpServer()).get(`/v1/content-items/${second.id}/instagram-collaborators/proofs/proof-from-${first.id}/status`).expect(200);expect(status.body).toEqual({trackingStatus:"not_started",providerReadComplete:false,availability:"not_fetched",snapshots:[]});});
  it("uses a safe mock publisher identity instead of the account display label",async()=>{const now=new Date().toISOString();await infrastructure.connectedAccountRepository.save({id:"instagram-display-label-account",workspaceId:"default",brandId:"brand_default",platform:"instagram",displayName:"Analytics QA Instagram",externalAccountId:"analytics-qa-instagram",capabilities:["profile_read","media_publish"],status:"healthy",createdBy:"local-owner",createdAt:now,updatedAt:now},{id:"audit-instagram-display-label-account",workspaceId:"default",actorId:"local-owner",actorType:"human",action:"test.account-created",detail:{},createdAt:now});const item=await prepared();const capability=await request(app.getHttpServer()).get(`/v1/content-items/${item.id}/instagram-collaborators/capability?accountId=instagram-display-label-account&draftId=${item.draftId}`).expect(200);expect(capability.body).toMatchObject({publishingUsername:"analytics_qa_instagram",capability:{state:"supported"}});});
  it("rejects a manually reconciled provider result when its invite evidence does not match the approved target",async()=>{const preparedItem=await prepared();const candidate=await request(app.getHttpServer()).post(`/v1/content-items/${preparedItem.id}/instagram-collaborators/candidates`).send({draftId:preparedItem.draftId,accountId:"instagram-collab-account",collaborators:["guest"]}).expect(201);const approved=await request(app.getHttpServer()).post(`/v1/content-items/${preparedItem.id}/instagram-collaborators/candidates/${candidate.body.id}/approve`).send({}).expect(201);const scheduleBody={platform:"instagram",accountId:"instagram-collab-account",draftId:preparedItem.draftId,scheduledFor:"2099-01-01T12:00:00.000Z",deliveryMode:"auto_publish",instagramCollaboratorApprovalId:approved.body.approvalId};const scheduled=await request(app.getHttpServer()).post(`/v1/content-items/${preparedItem.id}/schedule`).send(await withCurrentScheduleConflictAcknowledgement(app,preparedItem.id,scheduleBody)).expect(201);const target=scheduled.body.targets.at(-1);const actor:Actor={id:"originpost-worker",name:"OriginPost Worker",role:"owner"};const started=startPublishAttempt(scheduled.body,target.id,`publish:${target.id}:v1`,actor,"job-collab-recovery");await infrastructure.repository.commit(started.item,started.event);const waiting=markTargetStatus(started.item,target.id,"action_required",actor,{reason:"provider_result_uncertain"});await infrastructure.repository.commit(waiting.item,waiting.event);const expectedInvite=collaboratorInviteProof(target.settings,"facebook_login");const operation:ProviderPublishOperation={id:"provider-operation-collab-forged",workspaceId:"default",contentItemId:preparedItem.id,targetId:target.id,attemptId:started.attempt.id,platform:"instagram",accountId:"instagram-collab-account",draftSha256:waiting.item.drafts.find((entry)=>entry.id===preparedItem.draftId)!.contentSha256,approvedSettingsSha256:target.settings.approvedSettingsSha256,status:"uncertain",containerId:"container-collab",childContainerIds:[],collaboratorInviteProof:{...expectedInvite,requestedUsernamesSha256:"0".repeat(64)} as never,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await infrastructure.providerPublishOperationRepository.save(operation);await request(app.getHttpServer()).post(`/v1/content-items/${preparedItem.id}/targets/${target.id}/provider-confirm`).set("if-match",String(waiting.item.version)).send({externalPostId:"media-collab",liveUrl:"https://www.instagram.com/p/collab/",publishedAt:new Date().toISOString(),disclosure:"none"}).expect(409);});
  it("derives and approves a custom Reel cover from same-brand ready media",async()=>{const item=await preparedReel();const candidate=await request(app.getHttpServer()).post(`/v1/content-items/${item.id}/instagram-collaborators/candidates`).send({draftId:item.draftId,accountId:"instagram-collab-account",collaborators:[],shareToFeed:false,reelCover:{mode:"custom_image",mediaId:item.cover.id}}).expect(201);expect(candidate.body.settings).toMatchObject({collaborators:[],shareToFeed:false,reelCover:{mode:"custom_image",mediaId:item.cover.id,mediaSha256:item.cover.sha256},approvedSettingsSha256:expect.stringMatching(/^[a-f0-9]{64}$/)});const approved=await request(app.getHttpServer()).post(`/v1/content-items/${item.id}/instagram-collaborators/candidates/${candidate.body.id}/approve`).send({note:"Checked the exact cover"}).expect(201);const scheduleBody={platform:"instagram",accountId:"instagram-collab-account",draftId:item.draftId,scheduledFor:"2099-01-01T12:00:00.000Z",deliveryMode:"auto_publish",instagramPublishApprovalId:approved.body.approvalId};const scheduled=await request(app.getHttpServer()).post(`/v1/content-items/${item.id}/schedule`).send(await withCurrentScheduleConflictAcknowledgement(app,item.id,scheduleBody)).expect(201);expect(scheduled.body.targets.at(-1).settings).toMatchObject({shareToFeed:false,reelCover:{mode:"custom_image",mediaId:item.cover.id,mediaSha256:item.cover.sha256},approvalBinding:{approvedSettingsSha256:candidate.body.settings.approvedSettingsSha256}});});
  it("binds the native AI-label choice and records requested versus observed proof",async()=>{
    const preparedItem=await prepared();
    const candidate=await request(app.getHttpServer()).post(`/v1/content-items/${preparedItem.id}/instagram-collaborators/candidates`).send({draftId:preparedItem.draftId,accountId:"instagram-collab-account",collaborators:[],isAiGenerated:true}).expect(201);
    expect(candidate.body.settings).toMatchObject({collaborators:[],isAiGenerated:true,approvedSettingsSha256:expect.stringMatching(/^[a-f0-9]{64}$/)});
    const approved=await request(app.getHttpServer()).post(`/v1/content-items/${preparedItem.id}/instagram-collaborators/candidates/${candidate.body.id}/approve`).send({note:"Native label checked"}).expect(201);
    const scheduleBody={platform:"instagram",accountId:"instagram-collab-account",draftId:preparedItem.draftId,scheduledFor:"2099-01-01T12:00:00.000Z",deliveryMode:"auto_publish",instagramPublishApprovalId:approved.body.approvalId};
    const scheduled=await request(app.getHttpServer()).post(`/v1/content-items/${preparedItem.id}/schedule`).send(await withCurrentScheduleConflictAcknowledgement(app,preparedItem.id,scheduleBody)).expect(201);
    const target=scheduled.body.targets.at(-1);
    expect(target.settings).toMatchObject({isAiGenerated:true,approvalBinding:{approvedSettingsSha256:candidate.body.settings.approvedSettingsSha256}});
    const actor:Actor={id:"originpost-worker",name:"OriginPost Worker",role:"owner"};
    const started=startPublishAttempt(scheduled.body,target.id,`publish:${target.id}:v1`,actor,"job-ai-recovery");
    await infrastructure.repository.commit(started.item,started.event);
    const waiting=markTargetStatus(started.item,target.id,"action_required",actor,{reason:"provider_result_uncertain"});
    await infrastructure.repository.commit(waiting.item,waiting.event);
    const operation:ProviderPublishOperation={id:"provider-operation-ai",workspaceId:"default",contentItemId:preparedItem.id,targetId:target.id,attemptId:started.attempt.id,platform:"instagram",accountId:"instagram-collab-account",draftSha256:waiting.item.drafts.find((entry)=>entry.id===preparedItem.draftId)!.contentSha256,approvedSettingsSha256:target.settings.approvedSettingsSha256,instagramAiDisclosureRequested:true,status:"uncertain",containerId:"container-ai",childContainerIds:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
    await infrastructure.providerPublishOperationRepository.save(operation);
    const confirmed=await request(app.getHttpServer()).post(`/v1/content-items/${preparedItem.id}/targets/${target.id}/provider-confirm`).set("if-match",String(waiting.item.version)).send({externalPostId:"media-ai",liveUrl:"https://www.instagram.com/p/ai-labelled/",publishedAt:new Date().toISOString(),disclosure:"ai-assisted"}).expect(201);
    expect(confirmed.body.proofs.at(-1)).toMatchObject({disclosure:"ai-assisted",instagramAiDisclosure:{requested:true,observed:true,label:"ai_info"},approvedSettingsSha256:candidate.body.settings.approvedSettingsSha256});
  });
});
