"use client";
import { AlertTriangle, BarChart3, CalendarClock, CheckCircle2, Clock3, Pause, Play, RefreshCw, RotateCcw, ShieldCheck } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { apiFetch, type AuthView } from "@/lib/api-client";

type Candidate={contentItemId:string;proofId:string;title:string;platform:"instagram"|"facebook"|"youtube";accountId:string;publishedAt:string;metricLabel?:string;metricValue?:number;autoEligible:false;blockers:string[]};
type Entry={id:string;version:number;name:string;sourceContentItemId:string;sourceProofId:string;platform:string;mode:"review_first";intervalDays:number;timezone:string;nextPublishAt:string;endAt:string;maxOccurrences:number;occurrenceCount:number;status:"active"|"paused"|"completed";manualReason?:string};
type Occurrence={id:string;occurrenceNo:number;scheduledFor:string;status:"processing"|"review_ready"|"scheduled"|"published"|"action_required"|"failed";contentItemId:string;proofId?:string;freshnessFlags?:string[];error?:string};
type Summary={active:number;paused:number;completed:number;needsReview:number};
const localInput=(date:Date)=>{const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};
const displayDate=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const count=new Intl.NumberFormat(undefined,{notation:"compact",maximumFractionDigits:1});

export function ReuseStudio({auth,workspaceId,brandId,onOpenContent}:{auth:AuthView;workspaceId:string;brandId:string;onOpenContent?:(id:string)=>void}){
 const [candidates,setCandidates]=useState<Candidate[]>([]);const [entries,setEntries]=useState<Entry[]>([]);const [summary,setSummary]=useState<Summary>({active:0,paused:0,completed:0,needsReview:0});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [message,setMessage]=useState("");const [selected,setSelected]=useState<Candidate|null>(null);const [selectedEntry,setSelectedEntry]=useState<Entry|null>(null);const [occurrences,setOccurrences]=useState<Occurrence[]>([]);const [busy,setBusy]=useState(false);
 const role=auth.memberships.find((membership)=>membership.workspaceId===workspaceId)?.role??"viewer";const canManage=role==="owner"||role==="manager";
 const load=useCallback(async()=>{setLoading(true);setError("");try{const query=`workspaceId=${encodeURIComponent(workspaceId)}&brandId=${encodeURIComponent(brandId)}`;const [candidateResponse,entryResponse,summaryResponse]=await Promise.all([apiFetch(`/v1/evergreen/candidates?${query}`,{cache:"no-store"},auth.csrfToken),apiFetch(`/v1/evergreen?${query}`,{cache:"no-store"},auth.csrfToken),apiFetch(`/v1/evergreen/summary?${query}`,{cache:"no-store"},auth.csrfToken)]);if(!candidateResponse.ok||!entryResponse.ok||!summaryResponse.ok)throw new Error("Could not load the reuse queue.");setCandidates(await candidateResponse.json() as Candidate[]);setEntries(await entryResponse.json() as Entry[]);setSummary(await summaryResponse.json() as Summary);}catch(value){setError(value instanceof Error?value.message:"Could not load the reuse queue.");}finally{setLoading(false);}},[auth.csrfToken,brandId,workspaceId]);
 useEffect(()=>{void load()},[load]);
 const top=useMemo(()=>candidates.slice(0,8),[candidates]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setBusy(true);setError("");setMessage("");const form=new FormData(event.currentTarget);const first=new Date(String(form.get("firstPublishAt")));const end=new Date(String(form.get("endAt")));const manualReason=String(form.get("manualReason")??"").trim();if(selected.metricValue===undefined&&!manualReason){setError("Tell the team why this post is worth refreshing when performance data is missing.");setBusy(false);return;}try{const response=await apiFetch("/v1/evergreen",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId,brandId,sourceContentItemId:selected.contentItemId,sourceProofId:selected.proofId,name:String(form.get("name")),mode:"review_first",intervalDays:Number(form.get("intervalDays")),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,firstPublishAt:first.toISOString(),endAt:end.toISOString(),maxOccurrences:Number(form.get("maxOccurrences")),...(manualReason?{manualReason}:{})})},auth.csrfToken);const body=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(body.message??"Could not create this reuse cycle.");setSelected(null);setMessage("Reuse cycle created. OriginPost will prepare a fresh draft before each date.");await load();}catch(value){setError(value instanceof Error?value.message:"Could not create this reuse cycle.");}finally{setBusy(false);}}
 async function inspect(entry:Entry){setSelectedEntry(entry);const response=await apiFetch(`/v1/evergreen/${encodeURIComponent(entry.id)}?workspaceId=${encodeURIComponent(workspaceId)}`,{cache:"no-store"},auth.csrfToken);if(response.ok){const body=await response.json() as {occurrences:Occurrence[]};setOccurrences(body.occurrences);}else setOccurrences([]);}
 async function change(entry:Entry,action:"pause"|"resume"){setBusy(true);setError("");try{const response=await apiFetch(`/v1/evergreen/${encodeURIComponent(entry.id)}/${action}?workspaceId=${encodeURIComponent(workspaceId)}`,{method:"POST",headers:{"if-match":String(entry.version)}},auth.csrfToken);const body=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(body.message??`Could not ${action} this cycle.`);setMessage(action==="pause"?"Cycle paused.":"Cycle resumed without backfilling missed dates.");await load();}catch(value){setError(value instanceof Error?value.message:"Could not update this cycle.");}finally{setBusy(false);}}
 if(loading)return <section className="module-page reuse-page"><div className="module-hero"><div><p className="eyebrow">REUSE STUDIO</p><h1>Loading proven posts…</h1></div></div></section>;
 return <section className="module-page reuse-page">
  <div className="module-hero reuse-hero"><div><p className="eyebrow">PROOF → FRESH DRAFT → APPROVAL</p><h1>Reuse proven posts safely</h1><p>OriginPost prepares a new draft each time. A person checks facts, media rights, and wording before anything is scheduled.</p></div><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={15}/> Refresh</button></div>
  {error?<div className="module-error" role="alert"><AlertTriangle size={16}/>{error}</div>:null}{message?<div className="success-banner" role="status"><CheckCircle2 size={16}/>{message}</div>:null}
  <div className="reuse-summary"><div><strong>{summary.active}</strong><span>Active cycles</span></div><div><strong>{summary.needsReview}</strong><span>Fresh drafts to review</span></div><div><strong>{summary.paused}</strong><span>Paused</span></div><div><strong>{summary.completed}</strong><span>Completed</span></div></div>
  <div className="reuse-grid">
   <section className="panel reuse-candidates"><div className="panel-title"><div><h2>Published candidates</h2><p>Performance stays provider-native. Missing numbers stay missing.</p></div></div>
    {!top.length?<div className="empty-state"><BarChart3 size={24}/><h3>No published proof yet</h3><p>Publish a post first. It will appear here with its proof and available analytics.</p></div>:<div className="reuse-card-list">{top.map((candidate)=><button key={candidate.proofId} className={`reuse-candidate ${selected?.proofId===candidate.proofId?"selected":""}`} onClick={()=>setSelected(candidate)}><span className={`platform-dot ${candidate.platform}`}/><div><strong>{candidate.title}</strong><small>{candidate.platform} · Published {displayDate(candidate.publishedAt)}</small><p>{candidate.metricValue===undefined?"Performance data unavailable":`${candidate.metricLabel}: ${count.format(candidate.metricValue)}`}</p>{candidate.blockers[0]?<em>{candidate.blockers[0]}</em>:<em>Ready for a human-checked refresh</em>}</div></button>)}</div>}
   </section>
   <section className="panel reuse-builder"><div className="panel-title"><div><h2>New refresh cycle</h2><p>{selected?`Using “${selected.title}”`:"Choose a published candidate first."}</p></div></div>
    <form onSubmit={(event)=>void create(event)}><label>Cycle name<input name="name" required maxLength={120} defaultValue={selected?`${selected.title} refresh`:""}/></label><div className="reuse-form-row"><label>Every<select name="intervalDays" defaultValue="30"><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option></select></label><label>Maximum repeats<input name="maxOccurrences" type="number" min="1" max="52" defaultValue="4" required/></label></div><label>Prepare first draft by<input name="firstPublishAt" type="datetime-local" min={localInput(new Date(Date.now()+15*60_000))} defaultValue={localInput(new Date(Date.now()+7*24*60*60_000))} required/></label><label>Stop after<input name="endAt" type="datetime-local" min={localInput(new Date(Date.now()+24*60*60_000))} defaultValue={localInput(new Date(Date.now()+180*24*60*60_000))} required/></label><label>Why is this worth refreshing?<textarea name="manualReason" maxLength={300} placeholder={selected?.metricValue===undefined?"Required because performance data is unavailable":"Optional editorial note"}/></label><div className="reuse-safety"><ShieldCheck size={17}/><p>No endless loop. No old approval. Every cycle makes a new draft and waits for a person.</p></div><button className="primary-button" disabled={!selected||!canManage||busy}>{busy?"Saving…":"Create refresh cycle"}</button>{!canManage?<small>Only a manager or owner can create a cycle.</small>:null}</form>
   </section>
  </div>
  <section className="panel reuse-policies"><div className="panel-title"><div><h2>Refresh cycles</h2><p>Pause is immediate. Resume starts from the next future date and never posts a missed burst.</p></div></div>{!entries.length?<div className="empty-state"><RotateCcw size={24}/><h3>No cycles yet</h3><p>Choose a proven post above to start one.</p></div>:<div className="reuse-policy-list">{entries.map((entry)=><article key={entry.id} className={`reuse-policy ${entry.status}`}><button className="reuse-policy-main" onClick={()=>void inspect(entry)}><span><strong>{entry.name}</strong><small>{entry.platform} · every {entry.intervalDays} days · {entry.occurrenceCount}/{entry.maxOccurrences} prepared</small></span><span className="reuse-next"><Clock3 size={14}/>{entry.status==="completed"?"Complete":entry.status==="paused"?"Paused":displayDate(entry.nextPublishAt)}</span></button><div className="reuse-policy-actions"><button onClick={()=>onOpenContent?.(entry.sourceContentItemId)}>Source proof</button>{entry.status!=="completed"&&canManage?<button onClick={()=>void change(entry,entry.status==="paused"?"resume":"pause")} disabled={busy}>{entry.status==="paused"?<><Play size={14}/> Resume</>:<><Pause size={14}/> Pause</>}</button>:null}</div>{selectedEntry?.id===entry.id?<div className="reuse-ledger"><h3>Cycle history</h3>{!occurrences.length?<p>No draft has been prepared yet.</p>:occurrences.map((occurrence)=><div key={occurrence.id}><CalendarClock size={15}/><span><strong>Cycle {occurrence.occurrenceNo}: {occurrence.status.replaceAll("_"," ")}</strong><small>{displayDate(occurrence.scheduledFor)}{occurrence.freshnessFlags?.[0]?` · ${occurrence.freshnessFlags[0]}`:""}{occurrence.error?` · ${occurrence.error}`:""}</small></span>{occurrence.status==="review_ready"?<button onClick={()=>onOpenContent?.(occurrence.contentItemId)}>Open draft</button>:null}</div>)}</div>:null}</article>)}</div>}</section>
 </section>;
}
