import { instagramRequestedUsernamesHash, type ContentItem, type ContentItemRepository, type InstagramCollaboratorCandidate } from "@originpost/domain";
import { describe, expect, it } from "vitest";
import { InMemoryInstagramCollaboratorRepository } from "../src/instagram-collaborator-repository.js";

function repositoryFor(item:ContentItem){const content={get:async(workspaceId:string,id:string)=>workspaceId===item.workspaceId&&id===item.id?structuredClone(item):null} as ContentItemRepository;return new InMemoryInstagramCollaboratorRepository(content);}
function item():ContentItem{const usernames=["guest"];const requestedUsernamesSha256=instagramRequestedUsernamesHash(usernames);const approvedSettingsSha256="a".repeat(64);return{workspaceId:"workspace-a",brandId:"brand-a",id:"content-a",targets:[{id:"target-a",platform:"instagram",accountId:"account-a",draftId:"draft-a",scheduledFor:"2026-08-29T10:00:00.000Z",deliveryMode:"auto_publish",status:"published",settings:{collaborators:usernames,approvedSettingsSha256,approvalBinding:{platform:"instagram",accountId:"account-a",draftSha256:"b".repeat(64),approvedSettingsSha256,canonicalSha256:"c".repeat(64)}}}],proofs:[{id:"proof-a",contentItemId:"content-a",draftId:"draft-a",draftSha256:"b".repeat(64),platform:"instagram",accountId:"account-a",externalPostId:"media-a",liveUrl:"https://www.instagram.com/p/test/",publishedAt:"2026-08-29T10:00:00.000Z",captionSha256:"d".repeat(64),mediaSha256:[],connectorResponseSha256:"e".repeat(64),approvedBy:"owner",sourceIds:[],disclosure:"none",approvedSettingsSha256,collaboratorInviteProof:{requestedUsernames:usernames,requestedUsernamesSha256,requestState:"requested_unverified",providerConnectionMode:"facebook_login"}}]} as ContentItem;}

describe("Instagram collaborator persistence authority",()=>{
  it("derives polling lineage only from the stored proof and exact approved target",async()=>{const value=item();const repository=repositoryFor(value);const poll=await repository.createPollFromStoredProof("workspace-a","content-a","proof-a",{nextAttemptAt:"2026-08-29T10:01:00.000Z",expiresAt:"2026-09-05T10:00:00.000Z",maxAttempts:20});expect(poll).toMatchObject({workspaceId:"workspace-a",brandId:"brand-a",contentItemId:"content-a",proofId:"proof-a",accountId:"account-a",externalMediaId:"media-a",inviteProof:{requestedUsernames:["guest"]}});await expect(repository.createPollFromStoredProof("workspace-b","content-a","proof-a",{nextAttemptAt:"2026-08-29T10:01:00.000Z",expiresAt:"2026-09-05T10:00:00.000Z",maxAttempts:20})).resolves.toBeNull();});
  it("rejects a forged usernames hash or target account binding",async()=>{const badHash=item();badHash.proofs[0]!.collaboratorInviteProof={...badHash.proofs[0]!.collaboratorInviteProof!,requestedUsernamesSha256:"f".repeat(64)} as never;await expect(repositoryFor(badHash).createPollFromStoredProof("workspace-a","content-a","proof-a",{nextAttemptAt:"2026-08-29T10:01:00.000Z",expiresAt:"2026-09-05T10:00:00.000Z",maxAttempts:20})).resolves.toBeNull();const badAccount=item();badAccount.targets[0]!.accountId="account-b";await expect(repositoryFor(badAccount).createPollFromStoredProof("workspace-a","content-a","proof-a",{nextAttemptAt:"2026-08-29T10:01:00.000Z",expiresAt:"2026-09-05T10:00:00.000Z",maxAttempts:20})).resolves.toBeNull();});
  it("keeps normalized candidate settings immutable after input mutation and approval",async()=>{const repository=repositoryFor(item());const collaborators=["guest"];const candidate={id:"candidate-a",workspaceId:"workspace-a",brandId:"brand-a",contentItemId:"content-a",draftId:"draft-a",draftSha256:"b".repeat(64),accountId:"account-a",publishingUsername:"publisher",settings:{collaborators,approvedSettingsSha256:"a".repeat(64)},status:"pending_approval",requestedBy:"owner",requestedAt:"2026-08-29T10:00:00.000Z"} satisfies InstagramCollaboratorCandidate;await repository.createCandidate(candidate);collaborators[0]="changed";const approved=await repository.approveCandidate("workspace-a","content-a","candidate-a",{id:"approval-a",actorId:"owner",createdAt:"2026-08-29T10:01:00.000Z"});expect(approved.settings.collaborators).toEqual(["guest"]);expect((await repository.getApprovedCandidate("workspace-a","content-a","approval-a"))?.settings.collaborators).toEqual(["guest"]);});
  it("fences stale poll workers with the repository clock and keeps internal claims private",async()=>{let now=new Date("2026-08-29T10:00:00.000Z");const value=item();const content={get:async(workspaceId:string,id:string)=>workspaceId===value.workspaceId&&id===value.id?structuredClone(value):null} as ContentItemRepository;const repository=new InMemoryInstagramCollaboratorRepository(content,()=>now);await repository.createPollFromStoredProof("workspace-a","content-a","proof-a",{nextAttemptAt:"2026-08-29T10:00:00.000Z",expiresAt:"2026-09-05T10:00:00.000Z",maxAttempts:20});const [first]=await repository.claimDuePolls("worker-a","1900-01-01T00:00:00.000Z",1,120);expect(first?.claimId).toContain("worker-a:");now=new Date("2026-08-29T10:02:01.000Z");const [replacement]=await repository.claimDuePolls("worker-b","2999-01-01T00:00:00.000Z",1,120);expect(replacement?.claimId).toContain("worker-b:");await expect(repository.recordPollResult(first!,{snapshots:[],providerReadComplete:false,trackingComplete:false,availability:"transport_failed",capturedAt:now.toISOString(),retryAt:"2026-08-29T10:10:00.000Z"})).rejects.toMatchObject({code:"instagram_collaborator_poll_lease_lost"});const status=await repository.getStatus("workspace-a","content-a","proof-a");expect(status.poll).not.toHaveProperty("claimId");expect(status.poll).not.toHaveProperty("claimLeaseExpiresAt");});
  it("keeps a complete provider read scheduled until the invite becomes terminal",async()=>{let now=new Date("2026-08-29T10:00:00.000Z");const value=item();const content={get:async(workspaceId:string,id:string)=>workspaceId===value.workspaceId&&id===value.id?structuredClone(value):null} as ContentItemRepository;const repository=new InMemoryInstagramCollaboratorRepository(content,()=>now);await repository.createPollFromStoredProof("workspace-a","content-a","proof-a",{nextAttemptAt:now.toISOString(),expiresAt:"2026-09-05T10:00:00.000Z",maxAttempts:20});const [poll]=await repository.claimDuePolls("worker-a",now.toISOString(),1,120);const pending={workspaceId:"workspace-a",brandId:"brand-a",contentItemId:"content-a",proofId:"proof-a",accountId:"account-a",externalMediaId:"media-a",requestedUsernamesSha256:instagramRequestedUsernamesHash(["guest"]),username:"guest",status:"pending" as const,capturedAt:now.toISOString(),providerResponseSha256:"f".repeat(64)};await repository.recordPollResult(poll!,{snapshots:[pending],providerReadComplete:true,trackingComplete:false,availability:"available",capturedAt:now.toISOString(),rawResponseSha256:"e".repeat(64),retryAt:"2026-08-29T16:00:00.000Z"});await expect(repository.getStatus("workspace-a","content-a","proof-a")).resolves.toMatchObject({poll:{status:"pending",latestReadComplete:true,rawResponseSha256:"e".repeat(64),nextAttemptAt:"2026-08-29T16:00:00.000Z"},snapshots:[{status:"pending"}]});});
});
