import { describe,expect,it } from "vitest";
import { advanceRemoteCorrectionOperation,approveRemoteCorrectionRequest,canonicalSha256,createRemoteCorrectionRequest,InMemoryOutboxRepository,verifyRemovalProofChain,type AuditEvent,type PublishProof,type RemoteCorrectionSnapshotEvidence } from "@originpost/domain";
import { InMemoryRemoteCorrectionRepository } from "../src/index.js";

const digest=(value:unknown)=>canonicalSha256(value);
const publishProof:PublishProof={id:"proof-1",contentItemId:"content-1",draftId:"draft-1",draftSha256:digest("draft"),platform:"youtube",accountId:"account-1",externalPostId:"video-1",liveUrl:"https://youtube.example/watch",publishedAt:"2026-08-29T10:00:00.000Z",captionSha256:digest("caption"),mediaSha256:[digest("media")],connectorResponseSha256:digest("response"),approvedBy:"editor-1",sourceIds:["source-1"],disclosure:"none"};
const snapshot=():RemoteCorrectionSnapshotEvidence=>{const base={publishProofId:publishProof.id,contentItemId:publishProof.contentItemId,draftId:publishProof.draftId,draftSha256:publishProof.draftSha256,platform:publishProof.platform,accountId:publishProof.accountId,externalPostId:publishProof.externalPostId,providerOwnerId:"channel-1",state:"public",objectKind:"video",mutableState:{},observedAt:"2026-08-29T10:02:00.000Z",providerVersion:"youtube-data-v3"};return{...base,canonicalSha256:digest(base)};};
function approvedOperation(id:string,reason:string){const requested=createRemoteCorrectionRequest({id,workspaceId:"workspace-1",brandId:"brand-1",publishProof,mutation:{action:"delete_remote"},reason,requestedBy:"manager-1",requestedAt:"2026-08-29T10:01:00.000Z"});return approveRemoteCorrectionRequest({operation:requested,approval:{actorId:"owner-1",actorType:"human",approvedAt:"2026-08-29T10:03:00.000Z"},beforeSnapshot:snapshot()});}
function finalizing(id:string,reason:string){const approved=approvedOperation(id,reason);return advanceRemoteCorrectionOperation(advanceRemoteCorrectionOperation(approved,"pre_write","2026-08-29T10:04:00.000Z"),"finalizing","2026-08-29T10:05:00.000Z");}
const audit=(operationId:string):AuditEvent=>({id:`audit-${operationId}`,workspaceId:"workspace-1",contentItemId:"content-1",actorId:"worker",actorType:"system",action:"remote_correction.resolved",detail:{operationId},createdAt:"2026-08-29T10:07:00.000Z"});

describe("in-memory remote correction repository",()=>{
  it("serializes concurrent proof appends into one root-to-tip chain",async()=>{const repository=new InMemoryRemoteCorrectionRepository(new InMemoryOutboxRepository(),()=>new Date("2026-08-29T10:07:00.000Z"));const first=finalizing("operation-1","Remove the accidental first publication.");const second=finalizing("operation-2","Remove the independently duplicated publication.");await repository.create(first,audit(first.id));await repository.create(second,audit(second.id));await Promise.all([first,second].map((operation,index)=>repository.claim(operation.workspaceId,operation.id,`claim-${index+1}`,"reconcile","2026-08-29T10:05:30.000Z","2026-08-29T10:08:00.000Z")));const result=await Promise.all([first,second].map((operation,index)=>repository.resolveWithProof({workspaceId:operation.workspaceId,operationId:operation.id,expected:["finalizing"],claimId:`claim-${index+1}`,proofId:`removal-${index+1}`,evidence:{grade:"provider_confirmed",afterObservationSha256:digest(`absent-${index}`),providerReceiptSha256:digest(`receipt-${index}`),occurredAt:"2026-08-29T10:06:00.000Z",observedAt:"2026-08-29T10:06:30.000Z"},resolvedAt:"2026-08-29T10:07:00.000Z"},audit(operation.id))));const proofs=result.flatMap((entry)=>entry?[entry.proof]:[]);expect(proofs).toHaveLength(2);expect(verifyRemovalProofChain(publishProof,proofs)).toBe(true);});
  it("requires a matching unexpired provider claim and ignores a backdated resolvedAt",async()=>{const repository=new InMemoryRemoteCorrectionRepository(new InMemoryOutboxRepository(),()=>new Date("2026-08-29T10:07:00.000Z"));const operation=finalizing("operation-only","Remove the one incorrect publication.");await repository.create(operation,audit(operation.id));const base={workspaceId:operation.workspaceId,operationId:operation.id,expected:["finalizing"] as const,proofId:"removal-only",evidence:{grade:"provider_confirmed" as const,afterObservationSha256:digest("absent"),providerReceiptSha256:digest("receipt"),occurredAt:"2026-08-29T10:06:00.000Z",observedAt:"2026-08-29T10:06:30.000Z"},resolvedAt:"2026-08-29T10:06:45.000Z"};await expect(repository.resolveWithProof(base as never,audit(operation.id))).rejects.toThrow(/claim ID/i);await repository.claim(operation.workspaceId,operation.id,"expired-claim","reconcile","2026-08-29T10:05:30.000Z","2026-08-29T10:06:59.000Z");await expect(repository.resolveWithProof({...base,claimId:"expired-claim"},audit(operation.id))).resolves.toBeNull();await repository.claim(operation.workspaceId,operation.id,"active-claim","reconcile","2026-08-29T10:07:00.000Z","2026-08-29T10:08:00.000Z");const input={...base,resolvedAt:"2026-08-29T10:07:00.000Z",claimId:"active-claim"};await expect(repository.resolveWithProof(input,audit(operation.id))).resolves.not.toBeNull();await expect(repository.resolveWithProof({...input,proofId:"forged-second"},audit(operation.id))).resolves.toBeNull();});
  it("rejects expired claims before both pre-write and finalizing transitions",async()=>{const repository=new InMemoryRemoteCorrectionRepository(new InMemoryOutboxRepository(),()=>new Date("2026-08-29T10:10:00.000Z"));const approved=approvedOperation("operation-prewrite","Expired lease must not start a provider write.");await repository.create(approved,audit(approved.id));await repository.claim(approved.workspaceId,approved.id,"expired-prewrite","execute","2026-08-29T10:04:00.000Z","2026-08-29T10:05:00.000Z");const prewrite=advanceRemoteCorrectionOperation(approved,"pre_write","2026-08-29T10:04:30.000Z");await expect(repository.compareAndSet(prewrite,["approved"],audit(approved.id),[],"expired-prewrite")).resolves.toBe(false);expect((await repository.get(approved.workspaceId,approved.id))?.operation.status).toBe("approved");const prewriteStored=advanceRemoteCorrectionOperation(approvedOperation("operation-finalizing","Expired lease must not reach finalizing."),"pre_write","2026-08-29T10:04:00.000Z");await repository.create(prewriteStored,audit(prewriteStored.id));await repository.claim(prewriteStored.workspaceId,prewriteStored.id,"expired-finalizing","execute","2026-08-29T10:04:00.000Z","2026-08-29T10:05:00.000Z");const final=advanceRemoteCorrectionOperation(prewriteStored,"finalizing","2026-08-29T10:04:30.000Z");await expect(repository.compareAndSet(final,["pre_write"],audit(prewriteStored.id),[],"expired-finalizing")).resolves.toBe(false);expect((await repository.get(prewriteStored.workspaceId,prewriteStored.id))?.operation.status).toBe("pre_write");});
});
